bisdn/basebox

- configure.ac
- src/baseboxd/cbasebox.cpp
- src/roflibs/netlink/cnetlink.cpp
* fixed daemonize switch (now default to not daemonize if there is no daemonize switch)
* fixed wrong typecast for v6 neighbor addresses
* update to rofl-common
> updates to basebox

- src/roflibs/netlink/crtlink.hpp
- src/roflibs/netlink/crtneigh.hpp
- src/roflibs/netlink/ctapdev.cpp
- src/roflibs/netlink/ctapdev.hpp
- src/roflibs/netlink/tap_manager.cpp
- src/roflibs/of-dpa/cbasebox.cpp
- src/roflibs/of-dpa/cbasebox.hpp
mostly headers
and ctapdev:
* don't close tapdevs if open is called again
* check IFNAMSIZ of port name
* don't open/create tapdev during constructor, but during open
* remove obsolet pvid
> a bunch of cleanup

- src/roflibs/netlink/cpacketpool.cpp
initialization of local statics are thread-safe in c++11
> cpacketpool: fix multithreaded init of pool

- src/roflibs/netlink/ofdpa_bridge.cpp
no need to have them using glog
> logging: remove obsolet std::endl calls

- src/roflibs/netlink/cnetlink.cpp
- src/roflibs/netlink/nbi_impl.cpp
- src/roflibs/netlink/tap_manager.cpp
* remove link from registered links before deleting it:
E1028 18:06:13.851470 28380 cnetlink.cpp:195] handle_wakeup: no ifindex of port_id=5 found
E1028 18:07:17.923408 28380 cnetlink.cpp:711] neigh_ll_deleted: eRtLinkNotFound: crtlinks::get_link() / error: ifin
F1028 18:07:17.923449 28380 cnetlink.cpp:365] route_link_apply: insertion to registered_port_to_ifindex failed
* neigh_ll_deleted updated as well, since l2 fdb is updated later
* registered_port_to_ifindex was not erased
> fix race condition when link gets deleted

- src/roflibs/netlink/cnetlink.cpp
if no link was attached to a bridge, deletion of a link fails
> fix delete link

- configure.ac
Test for libgflags tests for main, which fails due to
-Winfinite-recursion. Now the test uses getenv.
> fix build using clang

- src/roflibs/netlink/ctapdev.cpp
- src/roflibs/netlink/ctapdev.hpp
- src/roflibs/netlink/nbi_impl.cpp
- src/roflibs/netlink/nbi_impl.hpp
- src/roflibs/netlink/tap_manager.cpp
- src/roflibs/netlink/tap_manager.hpp
every tap interface currently creates a thread for its io. This is now
merged into a single thread for performance reasonns.
use override syntax for rofl interface
> run tap io single threaded

- src/roflibs/netlink/nbi_impl.hpp
compilation on CentOS 7 failed due to this
> nbi: add missing include

- Vagrantfile
- configure.ac
- src/roflibs/netlink/tap_manager.cpp
- src/roflibs/of-dpa/cbasebox.cpp
- src/roflibs/of-dpa/cbasebox.hpp
* updated configure.ac & Vagrantfile
* renaming of function to adapt to rofl-common 0.12.0
* typos corrected
* make use of `set_txqueue_max_size` of rofl 0.12.0 to increase tx queue size
> rofl-common 0.12.0 adaptations

- salt/roots/basebox/repos.sls
Without the testing repos, basebox doesn't compile.
> Fix the salt states

- src/netlink/nl_l3.cpp
in case neighbour unreachablility detection is in state failed during
creation we can't add a neighbour
> neigh: ignore nud failed states

- src/of-dpa/ofdpa_datatypes.h
* the value of `OFDPA_OXM_ACTSET_OUTPUT` in the TTP seems to differ from ofagent, so we use 43 to be compatible to ofagent
> OFDPA_OXM_ACTSET_OUTPUT = 43

- src/basebox_api.cc
- src/basebox_api.h
- src/basebox_grpc_statistics.cc
- src/basebox_grpc_statistics.h
- src/baseboxd.cpp
- src/netlink/cnetlink.cpp
- src/netlink/cnetlink.hpp
- src/netlink/nbi_impl.cpp
- src/netlink/nbi_impl.hpp
- src/netlink/nl_bridge.cpp
- src/netlink/nl_bridge.hpp
- src/netlink/nl_l3.cpp
- src/netlink/nl_l3.hpp
- src/netlink/tap_manager.cpp
- src/netlink/tap_manager.hpp
Currently we just listen to events on ports we learned from the switch
api. To support additional ports we move the mapping of ifindex to
port_id (presented from the southbound api) to the tap_manager. Due to
this work cnetlink is no longer a singleton instance.
> architectural rework to support additional ports

- src/netlink/cnetlink.cpp
Occasionally the ifindex returned can be 0 and thus we run into the
assertion. This is fixed here with this PR.
> Do not run into assertion

- src/netlink/cnetlink.cpp
- src/netlink/cnetlink.hpp
actual link types that are not handled so far go into unsupported now
> differentiate between unknown and unsupported

- src/netlink/cnetlink.cpp
- src/netlink/tap_manager.cpp
- src/netlink/tap_manager.hpp
In case the datapath notifies a port removal and tries to add the port
again later this leads to a termination of the controller. The issue is
caused due to a not updated id:ifindex mapping which is fixed in the PR.
fixes f1d021e
> tap_manager: port id:ifindex mapping fixed

- src/netlink/tap_manager.cpp
in case some other tap device is removed we would stop here
> do not bother about other tap devices removed

- src/netlink/tap_manager.cpp
Do not fall through in this case statements to prevent a
double free.
> prevent possible double free

- src/of-dpa/controller.cpp
* fm is already sent by the function above (egress_port_vlan_remove)
> remove_fm_duplicate

- src/of-dpa/controller.cpp
IEEE has defined a set of ethernet multicast group addresses for specific purposes (01-80-C2-XX-XX-XX). According to IEEE 802.1D, all addresses within range 01-80-C2-00-00-00 to 01-80-C2-00-00-0F must not be forwarded by switching devices. This PR adds a call to rofl_ofdpa::enable_policy_8021d() so that all ethernet frames from the specified range ethernet destination address range is redirected to the upper controller entity.
> handling of ethernet multicast address group according to IEEE 802.1D

- src/basebox_api.cc
- src/basebox_api.h
This removes grpc relations from the basebox api header files.
> api: api cleanup

- src/netlink/nl_bridge.cpp
in case an interface was deleted or a vlan unconfigured the
l2 source cache is now cleared as well.
> nl_bridge: clear l2 cache

- src/netlink/cnetlink.cpp
- src/netlink/cnetlink.hpp
- src/netlink/netlink-utils.cpp
- src/netlink/netlink-utils.hpp
Deleted links may be deleted already from the netlink caches since they were read from the the callback. In this patch this is fixed by checking as well the queue of read netlink objects.
> cnetlink: fix several lookup issues

- .copr/Makefile
- .travis.yml
- pkg/testing/rpm/Makefile
Test the build in a recent docker build environment (currently F28). To
simplify dependency installation the testing spec file is being used and
therefor the Makefile was separated to support this.
> RFC: Buildsystem: build in docker on travis

- pkg/systemd/baseboxd.service
This just causes trouble and can be omitted
> systemd-service: remove network-online.target dependency

- configure.ac
in case libgrpc is not found with pkgconfig this adds a fallback which
uses AC_CHECK_LIB.
> autoconf: add AC_CHECK_LIB as fallback for grpc

- pkg/testing/rpm/Makefile
make -C pkg/testing/rpm creates now a src.rpm in the same folder without
the need of specifying the outdir. Furthermore the tarball is cleaned
after it is of no use.
> buildsystem: simplify testing build of src.rpm

- src/netlink/tap_manager.cpp
The iterator pos must be valid and dereferenceable. Thus the end()
iterator (which is valid, but is not dereferencable) cannot be used as a
value for pos.
From: https://en.cppreference.com/w/cpp/container/map/erase
fixes 63ed6733
> tap_manager: don't try to remove the end

- src/netlink/netlink-utils.cpp
Even so we get a bridge slave the bridge related changes are shown only
when the family is AF_BRIDGE. In this case we want to have the actual
interface type/kind.
fixes: b31c17c
> netlink: fix bridge port handling

- src/netlink/cnetlink.cpp
- src/netlink/cnetlink.hpp
Loopback address logic now fixed, restarting adds the previously existing addresses. 
Fixes f74c51d328bee27eb72f546780c9b3ffc8b982f6.
> Loopback address fixes

- .clang-tidy
- README.md
- meson.build
- scripts/run-clang-tidy-script.sh
- src/basebox_grpc_statistics.cc
- src/netlink/cnetlink.cc
- src/netlink/nl_bridge.cc
- src/netlink/nl_l3.cc
- src/netlink/nl_vxlan.cc
- src/netlink/tap_io.cc
- src/netlink/tap_manager.cc
- src/of-dpa/controller.cc
Run `ninja -C .build clang-tidy` to run clang-tidy on the source files. This depends on clang-tidy and runs faster when [run-clang-tidy.py](https://github.com/llvm-mirror/clang-tools-extra/blob/master/clang-tidy/tool/run-clang-tidy.py) is in your PATH.
> add clang-tidy target

- src/netlink/nl_bond.cc
- src/of-dpa/controller.cc
- src/sai.h
The implementation on the controller side is currently rather a mock
since currently no real lags with multiple ports can be implemented.
Therefore this just prepares for the use of a real lag later on.
> bond: return correct id when creating a lag

- src/netlink/cnetlink.cc
- src/netlink/cnetlink.h
- src/netlink/nl_bond.cc
- src/netlink/nl_bridge.cc
In case a bond interface was created before a port was enslaved the bond
can already be attached to a bridge and configured. So far the bridge
configuration was not possible. This PR adds support for this.
> bond: support late bridge attachemant

- src/netlink/nl_l3.cc
> nl_l3: fix ipv6 prefix length for host address

- src/netlink/nl_bond.cc
- src/netlink/nl_bond.h
- src/of-dpa/controller.cc
In case a bond existed in the systemd during initialization we do not
create a bond internally. As soon as an interface is attached to these
bonds we now allow late bond registration.
Minor bug fixed in the deletion of a lag_id in the controller stub that
is so far not used to create lags on the switch.
> bond: allow late registration of bonds

- src/netlink/nl_l3.cc
- src/netlink/nl_l3.h
Currently the deletion of an ip address leads to deletion of the
termination mac and therefore deleteion of an ip address may lead to
invalid bahaviour. This PR adds proper handling of the mac addresses by
tracking the port,vid,mac and ether type.
> nl_l3: proper handling of termination mac

- src/netlink/cnetlink.cc
- src/netlink/nl_l3.cc
- src/netlink/nl_l3.h
- src/of-dpa/controller.cc
- src/of-dpa/controller.h
- src/sai.h
All routes and host routes ecmp are with this PR ecmp ready. Currently
this is limited to existing neighbours. Furthermore this PR adds
handling to nexthop changes.
> l3: add ecmp

- src/netlink/nl_bridge.cc
- src/netlink/nl_bridge.h
- src/netlink/nl_vxlan.cc
In case a vxlan interface is attached without any endpoints the access
ports are not created. This PR transforms the access ports for this
case.
> update access ports

- src/netlink/nl_vxlan.cc
In case an endpoint configured is already configured we still have to
update the access ports.
fixes 350ec0b
> vxlan: udpate access ports for existing endpoints

- meson.build
in case glog is built using cmake there is currently no pkg-config file
> meson: lookup libglog without pkg-conig

- src/netlink/nl_l3.cc
- src/netlink/nl_vlan.cc
- src/netlink/nl_vlan.h
Counting refcounts for VLANs allows us to remove the L3 address safely, without removing the VLAN entry
> Vlan refcount

- src/netlink/cnetlink.cc
- src/netlink/nl_l3.cc
* While verifying the next hop while adding/deleting routes, [link to code](https://github.com/bisdn/basebox/blob/1378c8ae78ff6f739e2a89974be85e7a94d428f0/src/netlink/nl_l3.cc#L1167), the correct link could in certain ocasions not be found. This would lead to crashes on the is_bridge_interface function call. 
* In [link to code](https://github.com/bisdn/basebox/pull/219/files#diff-3c368f43e25d51e19a158722ea158133L1708) all of the relevant checks have been done, so we can exit the function with a simple else condition.
Two segfaults were found while testing the VRF feature. 
* One was related to restarting the on-switch endpoint after VRF configuration, which would trigger route deletion leading to a crash. 
* The other was running the VRF example script once, tearing it down, and running …
> Fix vrf segfault on deletion of VRFs

- src/basebox_grpc_statistics.cc
- src/of-dpa/controller.cc
This PR aims to fix the wrong statistics reported from baseboxd. We have discovered that Openflow was carrying the wrong statistics for the tx_errors counter, which is apparently unsupported in OF-DPA. The fix was disabling this counter permanently.
This is required to export the correct port stats from baseboxd, solving the wrongly reported tx_errors.
Tested by attaching the controller to a GRPC interface, and querying the port stats.
> fix: remove unsupported tx_errors from statistics

- src/netlink/nl_l3.cc
- src/netlink/nl_l3.h
- src/netlink/nl_l3_interfaces.h
On route addition, if the next-hop would not be previously known then the route would be ignored by baseboxd, resulting in broken state. This fix rewrites this logic, by adding first the route pointing to the controller, storing it internally, to wait for proper registration. After adding the neighbour, the route will be updated to point to the correct output interface, and routing will continue as normal.
This pull request will fix the bug reported in  #222, where routing will not work, in the case for unknown next-hops. 
The test was based on the script present  in #222, [Gist](https://gist.github.com/rubensfig/8f8ebd05444ac6b7709bf0d5ad5d6946)
> bug: fix late nexthop registration

- examples/routing/ECMP/01-controller
This PR will add the missing ECMP example script needed to correctly document this feature in baseboxd. 
It as well includes the target setup, and a short explanation on the feature itself. 
ECMP was introduced as a feature in #193, in order to support ECMP routing for VxLAN.  Currently the feature will only configure the ECMP routes when the next-hops have been learned/ configured, which is due to change in a following feature.  
This script has been tested against the latest BISDN Linux, with Linux Kernel v5.2.
> doc: add ECMP examples

- examples/bridging/qnq/qnq_vlan_controller
- examples/bridging/qnq/qnq_vlan_server
- src/netlink/cnetlink.cc
- src/netlink/cnetlink.h
- src/netlink/nl_bridge.cc
- src/netlink/nl_bridge.h
- src/of-dpa/controller.cc
- src/of-dpa/controller.h
- src/sai.h
This PR adds support to QnQ aware switching. This feature will allow baseboxd to write to the correct OFDPA table, thus setting the correct egress TPID.
The changes in the controller class add a new pair of functions: set_egress_tpid and delete_egress_tpid. These functions have been added to rofl-ofdpa in https://github.com/bisdn/rofl-ofdpa/pull/102, and return the correct flow mod to the switch.
On the netlink part, when a bridge is added with the command `ip l a bridge (...) vlan_protocol 802.1ad`, and ports are subsequently added to it, the sysfs value for the vlan_protocol is read (stored in  /sys/class/net/ + bridge_portname + /bridge/vlan_protocol) to determine if the entry in the TPID table must be set. In the case of a 802.1Q bridge, nothing is set; on a 802.1AD. the TPID entry on …
> QnQ Vlan support

- src/netlink/nl_bridge.cc
When a user tries to configure traditional bridges, and attach baseboxd's ports to it, the switch will accept it, but leads to errors, since this configuration is not currently supported in baseboxd. Therefore, reading the vlan_filtering option in the bridge interface sysfs is necessary to prevent misconfiguration. 
This PR also adds further exception handling to the functions introduced in #230,  set_egress_tpid, and delete_ingress_pid.
This PR aims to introduce a feature where baseboxd will prevent the user from configuring non-vlan aware bridges, since these can be created and used, but will lead to failures if that happens. 
The following list of commands should work correctly, resuming normal baseboxd's operation after.
```
ip link add swbridge type bridge vlan_filtering 1
ip link …
```
> Prevent VLAN unaware bridges from being configured

- src/netlink/cnetlink.cc
- src/netlink/cnetlink.h
- src/netlink/nbi_impl.cc
- src/netlink/nbi_impl.h
- src/netlink/tap_manager.cc
- src/netlink/tap_manager.h
- src/of-dpa/controller.cc
- src/sai.h
This PR changes the handling of the initial port status desc message, and subsequent port_status messages. 
The initial message contains the port description that is used to create the baseboxd interfaces, and has per-port config and state flags. These flags can be used to control the start up administrative state of a certain interface, via setting the ioctl SIOCGIFFLAGS to IFF_UP. This control is not exposed via netlink. 
These changes also remove any port handling from the cnetlink part, so all interface management is currently done by the tap_manager.
The port_status_changes function is also removed, optimizing the way southbound triggered interface changes are handled.
Currently baseboxd interfaces do not reflect any physical or administrative state. Initial layer 1 connectivity must …
> Handle interface status changes

- README.md
- meson.build
Fixed rofl-ofdpa dependency to reflect new version. Added meson check for version.
There was a costumer request claiming that basebox was breaking on executing a specific rofl-ofdpa call, so maintaining the version dependency will ensure correct version.
N/A
> meson: fix rofl-ofdpa dependency

- examples/bridging/trunk/cntl_trunk_script.sh
- src/netlink/cnetlink.cc
- src/netlink/nl_l3.cc
Adding a termination MAC entry after registering the link local address has a bug, where the wrong VID is discovered therefore writing the incorrect VLAN on the TMAC entry on the ASIC. 
This PR fixes VID discovery for the bridged ports, thus being able to write the correct VID. Also featured on this PR is a simplification of the addition of IP addresses, IPv4 and IPv6, and  
See #234. 
It effects not only systemd-networkd but also iproute2.
Configuring access ports on the switch means adding the PVID on the following rule,
inPort = ABC (Physical)  vlanId:mask = 0x0000:0x1fff (VLAN 0) | GoTo = 20 (Termination MAC) newVlanId = 0x1064 (VLAN XXX) | priority = 3 hard_time = 0 idle_time = 0 cookie = 21,
where XXX is then the PVID for a specific port ABC.
This bug i that this rule was written …
> nl_l3: do not create termination after registering link local addresses

- meson.build
Bumps the rofl ofdpa dependency to version 1.1.0, required after the #241 merge.
> build: update rofl-ofdpa dependency

- examples/tests/bridge_teardown.sh
This PR adds a new development directory for specific tests required to check baseboxd behaviour, and a test for bridge setup and teardown.
The bug #238 was reported, and for investigation the script in this PR was added. Besides the scripts used for development of features, it is useful to include support for some other, functionality-specific scripts.
> doc: add test for bridge setup and teardown

- src/netlink/nbi_impl.cc
- src/netlink/tap_manager.cc
This PR removes the modify port state capability from baseboxd. Due to not being able to accurately represent link admin and phy state, changing the port status on every notification will ensure that port configuration is removed, which brings the switch to a weird state on the retriggering of  the port state.
Rebooting servers must not change port state on the switch, to avoid losing configuration.
Tested against BISDN Linux v2.1.0
```
10-swbridge.netdev
[NetDev]
Name=swbridge
Kind=bridge
[Bridge]
DefaultPVID=0
VLANFiltering=1
```
```
10-swbridge.network
[Match]
Name=swbridge
[BridgeVLAN]
VLAN=108
````
```
20-port1.network
[Match]
Name=port1
[Network]
Bridge=swbridge
[BridgeVLAN]
VLAN=108
```
```
20-port3.network
[Match]
Name=port3
[Network]
Bridge=swbridge
[BridgeVLAN]
PVID=108 …
```
> tap_man: avoid changing interface state on modify

- examples/bridging/stp/01-server
- examples/bridging/stp/01-switch
Added example on how to setup a triangle topology between a switch with
one bridge and a server with two bridges, while configuring them to use
STP.
Port names in the examples are used between as4610-54t-2 and bbctrl01.
Signed-off-by: Ricardo Santos <ricardo.santos@bisdn.de>
> Added STP configuration example files

- src/of-dpa/ofdpa_client.h
fix compilation with gRPC v1.22.0 and newer
gRPC v1.22 moved the Channel implementation to its own class and changed
grpc::Channel to a typdef. This causes the following build failure:
```
In file included from ../git/src/of-dpa/controller.cc:16:
../git/src/of-dpa/ofdpa_client.h:12:7: error: using typedef-name 'grpc::Channel' after 'class'
12 | class Channel;
|       ^~~~~~~
In file included from /usr/include/grpcpp/grpcpp.h:52,
from /usr/include/grpc++/grpc++.h:26,
from ../git/src/of-dpa/controller.cc:13:
/usr/include/grpcpp/channel.h:26:30: note: 'grpc::Channel' has a previous declaration here
26 | typedef ::grpc_impl::Channel Channel;
|                              ^~~~~~~
```
Fix this by replacing the namespace declaration with using
grpc::Channel.
Newer distributions may use newer …
> fix compilation with gRPC v1.22.0 and newer

- src/of-dpa/controller.cc
Fix a race between enabling netlink handling after establishing the openflow connection from a switch, and the creation of port devices producing netlink events.
On connection from an openflow switch, we send multiple requests, and only after receiving a reply to the port_desc_request we enable handling of netlink messages.
But OF-DPA already treats sending the reply to the features_request earlier as a finished handshake, and will start sending port_status messages for all ports. If any of these can sneak in before the port_desc_request reply is received, they will trigger the creation of the appropriate tap devices, but netlink event handling is still disabled; effectively breaking these ports as critical internal state is not setup.
Later baseboxd will fail to assign netlink events …
> fix race in port tap device creation on of connection

- src/netlink/nbi_impl.cc
- src/of-dpa/controller.cc
- src/sai.h
The fix in #254 was not enough due to a misunderstanding of how rofl-common works. So instead of trying to figure out the place where to enable netlink processing without missing messages, just enable it always.
Mostly see #254, but now enable when instantiating nbi_impl, instead of waiting for the signal that the switch is ready.
See #254 
Two rounds of running the testing pipeline (with the pending carrier changes) on the ag7648, one round without the changes, build pipeline 9455 (currently running).
> properly fix race in port tap device creation on of connection

- src/netlink/nbi_impl.h
Fixes the following build error:
In file included from ../git/src/baseboxd.cc:10:
../git/src/netlink/nbi_impl.h:28:39: error: use of enum 'switch_state' without previous declaration
void switch_state_notification(enum switch_state) noexcept override;
^~~~~~~~~~~~
../git/src/netlink/nbi_impl.h:28:8: error: 'void basebox::nbi_impl::switch_state_notification(int)' marked 'override', but does not override
void switch_state_notification(enum switch_state) noexcept override;
^~~~~~~~~~~~~~~~~~~~~~~~~
> nbi_impl.h: remove missed prototype to fix compilation

- .travis.yml
- docker/from_source/Dockerfile
Instead of cloning within the container, just copy the currently checked
out sources into the container, which match the revision we want to
test. We still need to checkout the submodules.
This fixes travis always building master instead of the (PR) branch.
Travis does the testing for us ;-) (actually checking the travis build output and verifyfing the output contains the line "COMMIT=\<commit of this fix\>" appears in the log.
> .travis.yml: make sure we test the intended revision and not master

- src/netlink/ctapdev.cc
- src/netlink/nbi_impl.cc
- src/netlink/tap_manager.cc
Since Linux 5.0 it is possible to modify the carrier state of taptun devices, so let's use that to expose  the link state as carrier state and restore PORT_MODIFY handling.
By setting the carrier state on tap devices we can notify the system when a link is established or lost without touching the administrative state.
Changing the administrative state is inherently at conflict with any network management daemon controlling it. It will also override expected user behavior when intentionally setting a port down (next link up would set it up again).
So using the carrier state instead provides the link state on the correct channel, fixing/avoiding many of these issues.
A version containing this change was installed on Agema 5648 (Tomahawk+), Agema AG7648 (Trident II), Accton AS4610-54T-2 …
> show physical link state as carrier state on tap devices

- src/netlink/nbi_impl.cc
- src/netlink/tap_manager.cc
- src/netlink/tap_manager.h
- src/of-dpa/controller.cc
- src/of-dpa/controller.h
- src/sai.h
Link speed must be adapted to the correct reported speed from OFDPA. Currently the device is stuck at 10MB/s
```
ethtool port1 | grep Speed
Speed: 10Mb/s
```
Link speed for tap interfaces looks to be set at https://elixir.bootlin.com/linux/latest/source/drivers/net/tun.c#L3519
ethtool is able to change the speed with the ioctl `ioctl(3, SIOCETHTOOL, 0x7ffe47542930)`
The link speed is already reported from the switch, so baseboxd is capable of setting this information in Linux.
ethtool command: `ethtool -s port1 speed=100`
In Basebox, run 
```
PORT: Status (* indicates PHY link up)
*xe53    (40G) 
Settings for port54:
Supported ports: [ ]
Supported link modes:   Not reported
Supported pause frame use: No
Supports auto-negotiation: No
Supported FEC modes: Not reported
Advertised link modes: …
```
> tap_manager: set port speed on tap interfaces

- src/netlink/cnetlink.cc
- src/netlink/cnetlink.h
- src/netlink/netlink-utils.cc
- src/netlink/netlink-utils.h
- src/netlink/nl_bridge.cc
- src/netlink/nl_bridge.h
- src/of-dpa/controller.cc
- src/of-dpa/controller.h
- src/sai.h
In order to develop multicast, baseboxd must be aware of the modifications in the Linux kernel bridge driver multicast database. 
This database tracks the multicast memberships of ports in a certain bridge. The following is the available data in this database. 
```
dev swbridge 
port port7 
grp 239.1.0.31 
state temp
vid 108
```
This database is filled either manually via 
```
bridge mdb add dev <bridge> port <port> vid <VLAN id> grp <multicast group>
```
or via the incoming IGMP/MLD notifications from the hosts. These protocols allow the router to know which multicast group a certain host is interested in joining. 
The Linux kernel has a notification system via Netlink that reports the changes in the multicast database over the [RTNLGRP_MDB](https://elixir.bootlin.com/linux/latest/source/ …
> baseboxd: add Multicast Support on bridges

- src/netlink/cnetlink.cc
- src/netlink/nl_bridge.cc
prevent link local multicast to be configured on the switch
When initially developing multicast for baseboxd the structure of the libnl objects were unclear. As such, it was necessary to fix a couple problems with the implementation.
The change from executing on the libnl action (NL_ACT_NEW) to  acting on the message type, is to ensure that NL_ACT_CHANGE events correctly processed. 
We must also prevent the configuration of the link local multicast groups configured on IPv6 since these are not necessary for our purposes.
> multicast: fix bugs with implementation

- examples/bridging/stp/01-server
- examples/bridging/stp/01-switch
- meson.build
- src/netlink/nl_bridge.cc
- src/of-dpa/controller.cc
- src/of-dpa/controller.h
- src/of-dpa/ofdpa_client.cc
- src/of-dpa/ofdpa_client.h
- src/sai.h
The current PR aims to add xSTP support to baseboxd. 
The Linux bridges already implement STP, and baseboxd must only be made aware of the TAP interface changes between the STP states.
When the STP state changes on a TAP interface, the resulting port state is then written to the ASIC via ofdpa-grpc, which interacts with the ASIC to set the correct port state.
Adding STP support to baseboxd requires the following workflow:
```
STP port change
+
v
+---+----+
|baseboxd|
+---+----+
|
| gRPC
|
v
+----------+
|ofdpa-grpc|
+----------+
```
[ofdpa-grpc](https://gitlab.bisdn.de/basebox/ofdpa-grpc) must be adapted to be able to interact with the SDK. 
OpenFlow does not natively expose the capability of changing STP port state, as such we are forced to extend the existing side-channel to set this …
> Add STP support

- meson.build
- src/netlink/cnetlink.cc
- src/netlink/cnetlink.h
- src/netlink/nl_bond.cc
- src/netlink/nl_bond.h
- src/netlink/nl_bridge.cc
- src/netlink/nl_l3.cc
- src/netlink/nl_vlan.cc
- src/of-dpa/controller.cc
- src/of-dpa/controller.h
- src/of-dpa/ofdpa_client.cc
- src/of-dpa/ofdpa_client.h
- src/sai.h
The current bonding support in baseboxd does not implement the correct calls to the OF-DPA environment. This PR adds the necessary calls to the switch so that trunk ports can be handled in ASIC.
This PR adds as well the necessary changes to baseboxd to support enslaving bond interfaces to VLAN aware bridges.
> bond: expand bonding feature in baseboxd

- src/of-dpa/ofdpa_client.cc
Since we only establish the grpc connection to ofdpa-gprc after we
successfully created the openflow connection, there is a window where
the gprc connection isn't ready yet.
If it happens that we need to call any ofdpa grpc calls within this
window, these will fail, and the internal state becomes out of sync with
the linux state.
To avoid this, make grpc wait for the connection to be ready before
issuing rpc calls.
Fixes bonding configuration braking when setup by systemd-networkd on
switches with fast CPUs.
Ran the the bonding tests that consistently failed twice successfully in a row, currently running a full testing pipeline on two ag5648s
> of-dpa: make sure we wait for the ofdpa-grpc connection

- meson.build
- src/netlink/cnetlink.cc
- src/netlink/nl_bridge.cc
Instead of requiring a patches libnl, detect multicast support and only
enable the code for it when found.
Our multicast pull request has not been merged yet, and even if it does it will take a while until updated libnl versions will trickle down to distributions. To make it easier to build and test baseboxd with a system libnl, make the multicast functionality optional and dependent on libnl mdb support present.
Build baseboxd with a patched libnl, checked that it references in rtnl_mdb_* symbols.
Build baseboxd without a patched libnl, checked that it does not reference rtnl_mdb_* symbols.
> make multicast support optional

- src/netlink/cnetlink.cc
- src/netlink/nl_bond.cc
- src/netlink/nl_bridge.cc
Implement STP state support for bonded interfaces by passing on the state to the bonded interfaces.
The switch ASIC only supports setting STP state for physical ports, so we need to make sure that we propagate any STP state changes to the bonded interfaces. This also fixes an issue in get_port_id() that wasn't working with bridge interfaces for bond interfaces, only ones for tap interfaces.
STP is essential in many use cases.
Ran a pipeline with the changes applied on the ag5648s.
> implement stp for bond interfaces

- src/netlink/nl_l3.cc
Since we add vlan entries for all bond slaves, we also need to make sure
their vlan entries have the same vrf action.
Fixes (un)setting vrf for bond interfaces.
> nl_l3: fix vrf on bonds

- src/netlink/nl_vlan.cc
Don't hardcode VID 1 and untagged in the error path, and fix the error
messages to match what was attempted.
> nl_vlan: fix clean up on egress vlan add failure

- src/netlink/nl_l3.cc
- src/netlink/nl_l3.h
This PR aims to fix the creation of the key tuple used to identify L3 egress group entries added to a SVI. Instead of using both source and destination MAC addresses from the L2 neighbor, we now get these values from the SVI.
Adding a route via a next-hop IP located in a SVI results in the corresponding table 30 routing entry being sent to the controller, due to the key used to lookup the corresponding l3 egress group not being created correctly. Fixes https://github.com/bisdn/basebox/issues/275
See https://github.com/bisdn/basebox/issues/275 for a testing use case. With this PR, the routing entries are sent to the next-hop L3 egress group (and not to the controller)
> Fix lookup of L3 egress entries for SVIs

- src/netlink/cnetlink.cc
- src/netlink/cnetlink.h
- src/netlink/nl_bond.cc
- src/netlink/nl_bridge.cc
- src/netlink/nl_bridge.h
This PR aims to add support for QnQ bridging with a bonded interface as a bridge slave. In OFDPA, we have to enable the physical bond slaves to output with QnQ packets. 
Adding a bond interface to a bridge configured with `vlan_protocol 802.3ad` requires that the physical bond_slaves are configured in table 235 (Egress TPID). See https://github.com/bisdn/basebox/pull/230.
> Add support for QnQ bridging with bond slave interfaces

- src/of-dpa/controller.cc
This PR aims to expand multicast support in baseboxd by allowing bonded interfaces to be referenced in the l2 multicast groups.
The IGMP snooping entry is present on the ASIC and must be handled in baseboxd.
IGMP snooping is an implemented in baseboxd, but currently only has support for tap interfaces.
Ran multicast-ipv4_bonding_active-backup.playbook.yml
multicast-ipv4_bonding_lacp.playbook.yml
> Expand multicast support to bonds

- src/of-dpa/controller.cc
Signed-off-by: Rubens Figueiredo <rubens.figueiredo@bisdn.de>
This PR exposes error messages from the ASIC through logging.
Exposing the error messages we received is necessary to debug and see what the system is correctly working.
> controller: expose error message

- src/netlink/cnetlink.cc
- src/netlink/cnetlink.h
- src/netlink/nl_bond.cc
- src/netlink/nl_bond.h
- src/netlink/nl_l3.cc
- src/netlink/nl_l3.h
- src/of-dpa/controller.cc
This PR aims to expand trunking support, allowing users to set l3 addresses on bond interfaces. Code added expands functionality in nl_bond class.
Bonded interfaces also have support for IP addresses. Adding support to further L3 features, like routing daemons, requires that baseboxd correctly receives the bonding notifications, and translates this info to the switch.
Compiled with https://github.com/bisdn/rofl-ofdpa/pull/107.
Tests run:
- bgp-ipv4-lacp
- bgp-ipv4-active-backup
- bgp-ipv6-lacp
- bgp-ipv6-active-backup
- ospf-ipv4-lacp
- ospf-ipv4-active-backup
- ospf-ipv6-lacp
- ospf-ipv6-active-backup
- eigrp-ipv4-lacp
- eigrp-ipv4-active-backup
- rip-ipv4-lacp
- rip-ipv4-active-backup
> Add Support for l3 Addresses on trunk interfaces

- src/netlink/cnetlink.cc
- src/netlink/cnetlink.h
- src/netlink/nl_bond.cc
- src/netlink/nl_bond.h
- src/netlink/nl_bridge.cc
- src/netlink/nl_bridge.h
- src/netlink/nl_l3.cc
- src/netlink/nl_vlan.cc
- src/netlink/nl_vlan.h
Fix various issues with vlan on bond interface handling and centralize its code in `nl_vlan.cc`.
In preparation of better VRF handling, and to properly support SVIs on bond interfaces, the vlan code needs various fixes to handle it. This PR is an attempt at fixing this.
Testing pipelines have been run on as4610, ag5648 with the changes applied. All tests succeeded on ag5648, as4610 succeeded until one of the test servers became unavailable due to unknown causes.
> clean up and fix vlan handling for bonded interfaces

- src/netlink/nl_bridge.cc
If there already is a preexisting bonded interface attached to a bridge,
we might get a early version of the bridge interface that does not has
its kind set. This triggers a null pointer access in the assert.
To work around this, check for kind being set, and in absence, check if
the link's master is itself (which will be for the bridge).
The issue shows up in the journal as
```
Dec 02 20:29:30 agema-ag5648 baseboxd[2278]: I1202 20:29:30.747992  2305 cnetlink.cc:1092] link_updated: link enslaved port7
Dec 02 20:29:30 agema-ag5648 baseboxd[2278]: I1202 20:29:30.780452  2305 cnetlink.cc:977] link_created: using bridge bridge swbridge ether a6:6b:15:2b:97:17 master swbridge <broadcast,multicast,up>
Dec 02 20:29:30 agema-ag5648 kernel: Code: …
```
> nl_bridge: relax bridge rtnl_link requirement

- src/netlink/cnetlink.cc
- src/netlink/cnetlink.h
- src/netlink/nl_l3.cc
- src/netlink/nl_l3.h
- src/netlink/nl_vlan.cc
- src/netlink/nl_vlan.h
This PR aims to extend VRF support.  We have centralized all VRF handling on the nl_vlan classes, which then provides a clean way to configure VRFs on all interfaces, removing the specific order limitation that was present until the current PR. 
We have started tracking all of the VLAN - VRF mappings, so that it is easier to lookup the ids when we need to configure this.
This Pr extends the work done to support bond interfaces.
Ran pipelines including the trunk-vrf tests.
> Extend support for VRFs on bonded interfaces

- src/of-dpa/controller.cc
* add static flowmods to allow controller to receive IS-IS PDUs and drop
them from the pipeline (clearAction) to avoid packet duplication
Signed-off-by: Jan Klare <jan.klare@bisdn.de>
> add static flowmods to copy IS-IS PDUs to controller

- meson.build
- src/netlink/cnetlink.cc
- src/netlink/cnetlink.h
- src/netlink/netlink-utils.h
- src/netlink/nl_bond.cc
- src/netlink/nl_bridge.cc
- src/netlink/nl_bridge.h
- src/of-dpa/controller.cc
- src/of-dpa/controller.h
- src/of-dpa/ofdpa_client.cc
- src/of-dpa/ofdpa_client.h
- src/sai.h
This PR aims to add Per VLAN spanning tree state functionality to baseboxd, required by protocols like MSTP and PVST. 
This is achieved by tracking the VLAN Database changes in the kernel, that stores VLAN and STP states in all Linux interfaces(tap/bridge/bond/...). The kernel reports changes to the database via NETLINK messages RTM_GET/NEW/DELVLAN, and baseboxd is able to cache these messages via libnl. See: https://github.com/rubensfig/libnl/tree/bridge_vlandb
Setting the state on the ASIC is done via the gRPC connection, with the model from https://github.com/bisdn/basebox-protobuf/pull/9.
This PR adds receiving and parsing of VLAN Database STP states to nl_bridge, where all bridging related events are handled. We obtain the Kernel changes to the VLAN DB via NETLINK, and then process …
> baseboxd: implement per vlan spanning tree functionality

- src/netlink/nl_l3.cc
Reference counting was severily broken for l3 interfaces, which causes baseboxd trying to remove l3 unicast groups before we removed all references to them, causing ids being reused and a desync between baseboxd and openflow.
These commits attempt at fixing the most egregious instances, namely:
* nl_l3::add_l3_egress() not increasing the refcount for existing l3_interfaces
* nl_l3::add_l3_unicast_route() only getting the l3_interface_ids, but not increasing refcounts if they exist, but nl_l3::del_l3_unicast_route() always calling calling nl_l3::del_l3_neigh_egress(), leading to an imbalance in refcounts.
* nl_l3::del_l3_neigh_egress() not handling neighbors on bridge SVI interfaces
* nl_l3::add_l3_neigh(): creating an l3 egress interface before checking if the address should be handled …
> fix various issues with l3 interface handling

- src/netlink/nl_l3.cc
- src/netlink/nl_l3.h
Fix several issues preventing routes with unresolved nexthops being updated when the nexthop becomes available.
1. On adding l3 neighbors, when we check the nh_resolved_callbacks we compare the l3 address of the neighbor with the route destination networks waiting for a nexthop to become available. Fix this by comparing the l3 neighbor address with the nexthop address stored in the callback request's data instead.
2. The net_resolved_resolved callbacks only have the net, not the nexthop, which makes them unable to know when the nexthop becomes available for a route. Instead of trying to add this, just register for a nh_resolved_callback and drop the net_resolved_callback code.
3. The registered callbacks are stored in a `std:deque`, but `std:deque` behaves weird when removing elements …
> fix updating routes when nexthop becomes available

- src/netlink/nl_l3.cc
- src/netlink/nl_l3.h
- src/netlink/nl_l3_interfaces.h
- src/of-dpa/controller.cc
This PR deals with updating L3 egress entries. 
There are L3 egress entries being removed on IPv6 Link Layer addresses neigh removal. This is a mismatch since we are not refcounting ipv6 ll addresses.
Additionally, we have to track nexthop changes, more specifically updating routes over a nexthop when it turns unreachable. This is done via registering a route and its nexthop on addition, and waiting on this object until the corresponding nexthop gets deleted via del_l3_neigh. We then rewrite the route to controller, which is a mismatch to Linux state. Linux "wipes" the route from the kernel state, but we do not receive a specific notification for this event.
Internal static-route test on the 4610.
> nl_l3: update Link Layer Egress Entries

- src/netlink/nl_l3.cc
- src/netlink/nl_l3.h
In the case that a certain neighbor is pointing to another egress entry, on address addition we must rewrite the nexthop to point to controller
This use case is seen for example in VRRP.
Ran keepalived test
> nl_l3: add neigh search and update

- meson.build
Newer GCC versions require explicit linking against libs. Since we need
libpthread, we should properly pull it in as a depedency. Luckily there
is an easy meson dependency for that.
Fixes the following build error with yocto dunfell:
| FAILED: baseboxd
| x86_64-poky-linux-g++ -m64 -march=nehalem -mtune=generic -mfpmath=sse -msse4.2 -fstack-protector-strong -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/tmp/work/corei7-64-poky-linux/baseboxd/1.9.4-r0/recipe-sysroot  -o baseboxd 'baseboxd@exe/meson-generated_api_ofdpa.pb.cc.o' 'baseboxd@exe/meson-generated_common_empty.pb.cc.o' 'baseboxd@exe/meson-generated_common_openconfig-interfaces.pb.cc.o' 'baseboxd@exe/meson-generated_statistics_statistics-service.pb.cc.o' …
> properly link against libpthread if needed

- src/netlink/nl_l3.cc
IPv6 addresses are is 128 bits wide, not 32. Likely a copy and paste
error from the IPv4 code.
Pipelines using this code have ran over the weekend.
> nl_l3: fix prefix length check for IPv6 addresses

- src/netlink/cnetlink.cc
- src/netlink/cnetlink.h
- src/netlink/nl_bond.cc
- src/netlink/nl_bond.h
- src/netlink/nl_l3.cc
- src/netlink/nl_l3.h
Properly take over configured IP addresses and routes on (first) attachment to bond and bridge interfaces.
Currently the code does checks for ip and route configuration if it applies to interfaces linked to port interfaces, and ignores if it it doesn't. This makes sense at first, but breaks if the configuration might get added before port interfaces do get attached.
We do attempt to take over IP address configuration on bond interfaces, but miss configuration on linked vlan interfaces, and all configuration on bridge interfaces. Configured routes are completely ignored.
This PR attempts fixing the situation by expanding the code adding the ip addresses to also check all linked vlan interfaces, check the route cache for routes, and also call this on initial attachment to the bridge. …
> properly take over ip configuration on bridge/bond attachment

- src/netlink/nl_l3.cc
While the address space reserved for link local addresses is indeed
fe80::/10, the actual used network is fe80::/64. All link local
addresses assigned by the kernel or e.g. systemd follow that, so we can
just treat them like any other network address.
The onlink route is a /64, creating a /10 is wrong.
Testing pipeline run on Questone 2A with adapted flow checks.
> nl_l3: don't add fe80::/10 for IPv6 link local addresses

- src/netlink/nl_bond.cc
Only apply/scan for IP configuratiion when creating the bond interface, not on every update.
Currently we call add_ip_configuraiton multiple times for the same bond interface, on every update and new member.  This leads to ip configuration being parsed multiple times, which can easily lead to refcounting issues. 
Since we now only add IP configuration on creation, we also need to make sure that we only create a bond interface when we actually have an interface of our own to add.
We should try to stay consistent in our applied configuration, and try to not apply multiple times, especially if we want to be able to undo the changes on removal.
Weekend pipelines ran with this code and did not show any issues caused by it.
> nl_bond: only apply ip configuration once

- src/netlink/cnetlink.cc
Our code adding IP addresses and routes has checks for the bridge having
actual port or bond interfaces attached, else they will get ignored.
So we need to make sure that we do not create the bridge too early, and
only do so when the attached interface is one we track, i.e. has a
port_id.
Creating the bridge too early might lead to issues when applying the l3 configuration on it.
Weekend pipelines ran with this change applied.
> cnetlink: ignore bridge attachment for untracked interfaces

- src/netlink/nl_bond.cc
This PR adds a missing `<<` marker necessary for compiling.
compiled the code.
> nl_bond: add missing marker for VLOG

- src/netlink/nl_l3.cc
Only create a termination mac for non-locahost interfaces for IPv6, like
it is done for IPv4. Should reduce the log spam.
Localhost has no mac address (or rather all zeroes), so creation of termination mac interfaces will fail. So do not try to create them in the first place.
Weekend pipelines ran with it.
> nl_l3: align termination mac creation of IPv4 and IPv6 paths

- src/netlink/nl_l3.cc
Fix various issues with layer 3 neighbor handling on bridges.
Currently multiple codepaths related to updating and deleting layer 3 neighbors were not handling those on bridges due to a port id requirement for the interface, which bridge interfaces don't have.
Fix this by adding the appropriate resolution through the fdb to figure out the physical port, and allow any switch related port for updates.
This fixes the issue that l3 neighbors that were learned in failed state were never updated once they became reachable, were never triggering layer 3 interface creation and therefore no routing in hardware would be setup.
Test pipeline has been run on as4610, all tests passed.
> nl_l3: properly handle layer 3 neighbors on bridges

- meson.build
- src/netlink/cnetlink.cc
- src/netlink/nl_bridge.cc
The bridge vlan support is WIP and not yet submitted upstream. So to
allow building and using baseboxd without a patched libnl, add a check
for the new header and guard the code using it.
Fixes: 186326a ("cnetlink: add support for Linux RTM_NEW/DELVLAN messages;      * add libnl bridge-vlan cache support;")
Reported-by: Andreas Koepsel <andreas.koepsel@bisdn.de>
> make bridge vlan support in libnl optional

- src/netlink/cnetlink.cc
- src/netlink/cnetlink.h
- src/netlink/nl_bond.cc
When adding an IP address to an interface, we need to add vlan flows for
the untagged vlan. Since the assignment flows require physical ports,
we need to have them for all bond members.
Currently we do not add or a remove them when adding new members, so the
following flow would fail:
> sudo ip link add name bond1 type bond mode active-backup
> sudo ip link set port1 master bond1
> sudo ip address add 10.0.0.1/24 dev bond1
> sudo ip link set port2 master bond1
To fix this, add a new helper to know if a (bond) interface has any ip
addresses configured, and add the default vlan configuration to the port
in that case.
client_flowtable_dump 10 output:
Before:
> Table ID 10 (VLAN):   Retrieving all entries. Max entries = 12288, Current entries = 3.
> --  inPort = 1 (Physical)  vlanId:mask = …
> nl_bond: make sure to add the default vlan to new members if needed

- pkg/systemd/sysconfig.template
- src/baseboxd.cc
- src/netlink/cnetlink.cc
Multicast support is currently triggering unexpected behaviour where
DHCP packets do not get properly forwarded anymore. Until we identify
the cause, make it possible to disable multicast if encountering this
issue.
ran multicast-ipv4 test with FLAG_multicast=true => passed
ran multicast-ipv4 test with FLAG_multicast=false => failed due to missing flow table entries
> baseboxd: add a flag to make multicast support optional

- src/netlink/nl_l3.cc
nl::get_neighbor() might return known, but unreachable neighbors. If
this happens when deleting a route, we try then to pass this incomplete
neighbor to nl_l3::del_l3_egress, which will then trigger an assert, as
it expectes a complete neighbor.
Fixes the following crash seen on restart of FRR after reoute exchange
with eigrp:
```
Jul 21 11:27:17 agema-ag7648 baseboxd[2025]: I0721 11:27:17.681071  2079 nl_l3.cc:1425] get_neighbours_of_route: ifindex=8 gw=10.0.0.1
Jul 21 11:27:17 agema-ag7648 baseboxd[2025]: I0721 11:27:17.681125  2079 nl_l3.cc:1434] get_neighbours_of_route: get neigh=inet 10.0.0.1 dev bond2 <failed>
Jul 21 11:27:17 agema-ag7648 baseboxd[2025]:  of nh_addr=10.0.0.1
Jul 21 11:27:17 agema-ag7648 baseboxd[2025]: I0721 11:27:17.681174  2079 nl_l3.cc:1836] del_l3_unicast_route: …
```
> nl_l3: get_neighbours_of_route: treat neighbors without lladdr as unresolved

- src/netlink/cnetlink.cc
- src/netlink/cnetlink.h
- src/netlink/nl_l3.cc
- src/netlink/nl_l3.h
- src/of-dpa/controller.cc
This PR adds handling of changing MAC addresses on the TAP interfaces. When doing commands like,
```
$ ip link set PORT address MAC_ADDRESS 
```
The linux mac address will change to the one specified. When this change is triggered, kernel sends two notifications, the first one related to the change of the address itself. The next one will be flushing the ip neighs on the interface. 
The changing of mac addresses on the tap interfaces is relevant when there are IP addresses/ neighs/ routes configured on the interface. baseboxd must pick up the notification and change the entries in the termination mac table and egress l3 unicast group. Since there are maps following the entries in these tables, and associated refcounts, they must also be updated.
Setting new mac addresses in tap interfaces …
> Handle MAC address changes on tap interfaces

- pkg/systemd/sysconfig.template
Fix obvious typo supporrt, which should be support.
> sysconfig.template: fix typo supporrt => support

- src/netlink/cnetlink.cc
- src/netlink/nl_bridge.cc
With https://github.com/bisdn/meta-switch/pull/2 we simplify the libnl bridge vlan API. Since this changes the API, we need to update the code here as well.
Ran on tonights pipelines.
Depends on https://github.com/bisdn/meta-switch/pull/2
> Adapt libnl bridge vlan usage to updated API

- src/netlink/tap_manager.cc
We open a new socket every time we want to set the speed of a port, but
never close it. This eventually leads to hitting the maximum amount of
open file descriptors, leading to various other issues.
Fix this by closing the socket on return.
Fixes: b5fe46c ("tap_manager: set port speed on tap interfaces")
Running out of file descriptors breaks STP, since we check sysfs for the stp state of the bridge (which then fails).
1. set one port to up
2. Run `watch `'ls -l /proc/`pidof baseboxd`/fd | wc -l`` on switch
3. establish link on port
4. cut link on port
Before:
```
157 # initial state after boot
211 # port change notification flood after first link change
212 # port down again
````
After:
```
103 # initial state after boot
103 # port …
```
> tap_manager: do not leak socket when setting port speed

- src/of-dpa/controller.cc
Fix the following build error:
| In file included from ../git/src/of-dpa/controller.h:17,
|                  from ../git/src/of-dpa/controller.cc:16:
| ../git/src/of-dpa/controller.cc: In member function 'virtual int basebox::controller::ofdpa_stg_create(uint16_t)':
| ../git/src/of-dpa/controller.cc:2247:5: error: 'COMPACT_GOOGLE_LOG_ERRROR' was not declared in this scope; did you mean 'COMPACT_GOOGLE_LOG_ERROR'?
|  2247 |     LOG(ERRROR) << _FUNCTION__ << ": failed to allocate STG ID: " << stg_id;
|       |     ^~~
| ../git/src/of-dpa/controller.cc:2247:20: error: '_FUNCTION__' was not declared in this scope
|  2247 |     LOG(ERRROR) << _FUNCTION__ << ": failed to allocate STG ID: " << stg_id;
|       |                    ^~~~~~~~~~~
Fixes: 8139c13 ("controller: reuse deleted stg ids") …
> controller: fix typos that broke compilation

- src/netlink/nl_bridge.cc
Fix various issues in multicast handling to follow specs and allow IPv6.
Fixes the following issues in the multicast code:
* fix debug messages on removal
* align add and remove code to do the same checks
* do not abort on the first ignored entry (go through them all)
* do not create/remove groups for 224.0.0.0/8, these should always be flooded
* do not ignore ff02::/10, but only ff::/15 and ff02::1, allowing IPv6 snooping to actually work
Running a pipeline and updating the multicast-ipv4 test to handle the additional IPv6 groups created.
> fix various issues in multicast code and unbreak IPv6 snooping

- src/netlink/nl_l3.cc
Fix three small issues in the ip address removal paths that can lead to flows being left existing or deleted which shouldn't be. 
There are a few subtle difference between the code adding and the code removing flows for IP addresses that can lead to flows not being deleted, or being deleted too early.  there are three issues:
1. for IP address removals on any interface we tried to remove the corresponding unicast table flow, even if this wasn't our interface (e.g. the management interface)
2. We never removed termination mac entries for any interfaces without a port id, even we did add it (vlan interfaces on bridges)
3. We always tried to remove the vlan, even if we never added one because this interface was bridged, potentially leading to vlan flows being deleted that shouldn't be.
Fixes …
> nl_l3: align ip address removal to add

- src/of-dpa/controller.cc
When l3 neighbors that are also route nexthop become unavailable, we
will send in rapid succession an update for the route to point to
controller instead of the l3 unicast group, and the removal of the l3
unicast group.
If the removal is processed before the route update, the removal will
fail since it still is referenced by the route, and the l3 interface ids
in baseboxd and ofdpa become out of sync, causing various issues.
Fix this by adding a barrier before trying to remove the l3 unicast
group to ensure that any pending route updates finished processing.
> controller: l3_egress_remove: fix race with dropping references

- src/netlink/nl_bridge.cc
Signed-off-by: Hilmar Magnusson <hilmar.magnusson@bisdn.de>
LOG WARNING is given when learn_source_mac is run on an unconfigured port, the LOG message, however, does not contain the port/link name.
Added the link name to the LOG output.
I noticed this LOG in production, and I wanted to know which port it was receiving packets on.
On switch: attach port to bridge, add VID 3, no pvid.
On server attached to switch, add vlan interface on top of port with VID 10, and generate traffic. (I added an IP address to the interface and did a ping to a different address in the same subnet)
On current basebox we get this log:
```
learn_source_mac: got packet on unconfigured port
```
With patch we get:
```
learn_source_mac: got packet tagged with unconfigured vid = 10 on bridge link = bridge port7 ether …
```
> nl_bridge: add link name to LOG output

- src/netlink/nl_bridge.cc
- src/netlink/nl_vlan.cc
- src/netlink/nl_vlan.h
- src/of-dpa/controller.cc
- src/of-dpa/controller.h
- src/sai.h
By exposing the update parameter to the l2 group interface, the controller thread is able to trigger updates to the egress
tables, thus allowing to refresh the egress untagged setting on the respective group.
There was pending code handling the untagged changes to bridge interfaces.
This PR uncomments the code, allowing the egress_untagged updatesto bridge ports being translated into the southbound.
Fixes #266 
When updating an access ports, we must be able to configure the egress (un)tagged parameter on the ASIC.
If the interface is initially set without untagged, we cannot change this behaviour without deleting the port from the bridge and reconfiguring it. 
Tested with the following script
```
#!/bin/bash
ip link add name swbridge type bridge vlan_filtering 1 vlan_default_pvid 0
ip …
```
> bridging: implement update to vlan untagged

- src/netlink/nl_l3.cc
The check for avoiding adding the ::1/128 address is broken due to a
false AF.
Signed-off-by: Rubens Figueiredo <rubens.figueiredo@bisdn.de>
> nl_l3: fix check for address family

- src/netlink/cnetlink.cc
- src/netlink/cnetlink.h
- src/netlink/nl_bridge.cc
- src/netlink/nl_bridge.h
- src/of-dpa/controller.cc
- src/of-dpa/controller.h
- src/sai.h
Properly update forwarding entries for known neighbors moving to new ports.
Depends on OF-DPA changes actually notifying us about station moves.
Handle moving stations between ports by properly detecting if this happens, and updating the ext_learn entry in the kernel and the flow entry. 
Moving between ports may happen if e.g. people move their laptops, or if roaming from one AP to another. Not updating the entry means no connectivity until the old entry times out.
Tested on as4610 (and questone-2a with slightly different port names)
Switch 1:
```
ip link add name swbridge type bridge vlan_filtering 1
ip link set port2 master swbridge
ip link set port3 master swbridge
ip link set port54 master swbridge
ip link set swbridge up
ip link set port2 up
ip link set port3 up
ip link set port54 up …
```
> handle neighbors moving between ports

- src/netlink/nl_bridge.cc
When adding handling of untagged changes, it accidentially got added to
the loop processing the vlan diff, causing it to abort after the first
vlan, since it will process all untagged changes, then set done and
abort.
Fix this by moving the untagged_diff handling out of the vlan_diff
handling loop, so they cannot interfere with each other.
Config:
> $ bridge vlan show
> port              vlan-id
> swbridge          100
>                   101
>                   102
>                   111
> port54            100
>                   101
>                   102
>                   110
>                   111
>                   112
Before:
> $ client_flowtable_dump
> Table ID 10 (VLAN):   Retrieving all entries. Max entries = 16384, Current entries = 1.
> --  inPort = 54 (Physical) …
> nl_bridge: unbreak handling of bridge vlan changes with multiple vlans

- src/netlink/nl_bridge.cc
- src/of-dpa/controller.cc
- src/of-dpa/controller.h
- src/sai.h
Sinplify the SAI multicast interface into just join and leave calls, and hide the implementation details in controller.cc.
Currently l2 multicast handling is split into two sets functions, one for handling the multicast group and flow, and one for handling the joined ports to that group.
Since baseboxd does not track the number of group listeners, it needs the functions to tell it when to add or remove the group and flow. This makes it a bit awkward to use, so instead of forcing baseboxd to handle that, let the controller implementaton do that and just expose "generic" join and leave calls that do the flow/group creation in the background.
It makes the code a bit more clearer and understandable.
Running multicast-ipv{4,6} on questones.
> simplify layer 2 multicast SAI interface 

- src/netlink/nl_bridge.cc
- src/of-dpa/controller.cc
- src/of-dpa/controller.h
- src/sai.h
Make sure we properly drop all multicast references to L2 interfaces on bridge vlan removal so deletion of the group can succeed.
Both L2 unicast as multicast entries keep references to the l2 interface. On deletion of a bridge vlan, we drop the unicast entries, but not the mulicast entries, causing the deletion of the l2 interface to fail, and thus the port to stay in the vlan.
We cannot rely on the kernel for that, since the kernel does not flush the mdb on port vlan removal. So we need to drop them ourselves. But on the same time, in case the vlan comes back immediately, we need to rejoin to match the kernel state again, since the entries will still exist.
So add a new disabled state for l2 interfaces to keep a list of those that should exist, removed if the kernel deletes the mdb …
> drop multicast entries on bridge vlan removal

- src/netlink/cnetlink.cc
Make sure we do not try to handle l2 neighbors for other bridges, and be silent about them.
We may have additional bridges on the system, like `docker0`. So getting notifications about changes on a bridge without it being "our" bridge is perfectly normal.
Appearance of the docker bridge might cause issues due to not properly filtering the notifications.
Weekend pipeline on the AS4610.
> improve bridge ll neighbor handling

- src/netlink/cnetlink.h
- src/netlink/nl_bond.cc
- src/netlink/nl_bridge.cc
- src/netlink/nl_bridge.h
- src/of-dpa/controller.cc
- src/of-dpa/controller.h
- src/sai.h
Fix applying per vlan STP state for bond interfaces by applying the state to all members of the bond group.
STP state is a state of physical ports, not logical ports in the switch, so when the kernel changes the stp state of a bond interface of a bridge, we need to propagate the state to all members of the bond interface.
We also need to make sure that when adding or removing an interface to a bond group that is also part of a bridge that we apply the currently configured stp state to the new bond member, or deconfigure it when the interface leaves.
Allows using (M)STP on bridges with bond interfaces together.
Created a bridge with two bonds between both as4610 in testing (using ports 5/10 and 15/20), and checking the resulting stg stp states.
> fix applying per vlan STP state to bond interfaces

- src/netlink/nl_bridge.cc
When deleting a vlan on a port, we need to flush the local cache entries
for the link, not the bridge.
> nl_bridge: fix local cache flush on vlan removal

- src/netlink/nl_l3.cc
Deleting IP addresses from interfaces should remove references from termination MAC table, to ensure correct cleanup of state. 
As described in #362, by changing the MAC address on an interface, and attempting to delete the IP address of this interface, the entries do not seem to get removed. This is due to the cached link reference inside the address object that is about to be deleted. This reference is not updated after the MAC address change, which leads to wrong state being propagated.  
It is necessary for baseboxd to ensure that the state on the switch is cleanup correctly, and no flowtables are left pending.
```
ip address add 10.0.0.1/24 dev port1
ip link set port1 up 
ip link set address 02:01:01:02:01:02 dev port1
ip address delete 10.0.0.1/24 dev port1
```
Refer to #362 for …
> Fix tmac entries not being removed when cleaning up the IP address

- src/netlink/cnetlink.cc
- src/netlink/nl_bridge.cc
- src/netlink/nl_bridge.h
- src/netlink/nl_vxlan.cc
A recent fix for the kernel allows fdb entries to be switched to/from
ext_lern, so instead of inspecting every packet on reception, let the
kernel learn and take over fdb entries as ncessary.
Instead of trying to parse every incoming packet and try to learn the neighbors, just pass them on to the kernel and let it parse them, then handle the new neighbor notification.
This allows dropping the special handling in the RX path for bridges.
Adding support for Broadcom KNET intertfaces means we will not be able to inspect every packet, so we need to instead take over learned neighbors.
Running a pipeline on switches, but should be tested more.
> nl_bridge: take over fdb entries instead of creating them

- src/netlink/nl_l3.cc
- src/netlink/nl_vxlan.cc
Handle on-link routes like normal routes and don't add them as a side effect of handling ip addresses on interfaces.
Currently on-link routes are added indirectly when adding ip addresses with a non all-1 netmask. But the kernel notifies us about these routes as well, and we try to handle them, but due to special handling they always stay as unresolved.
So fix this by allowing on-link routes (without any ip next hops) to be added and removed, and drop the special handling for ip addresses.
As a side effect includes a fix for routes on vlan interfaces on ports.
This is a preparation for tackling the non-routed L3 neighbor handling (https://github.com/bisdn/basebox/issues/364). We need to know about on-link routes being added or going away, so we can determine if a neighbor is routable or …
> properly handle on-link routes

- meson.build
- pkg/systemd/sysconfig.template
- src/baseboxd.cc
- src/netlink/knet_manager.cc
- src/netlink/knet_manager.h
Add a port_manager implementation using Broadcom KNET interfaces
on switch.
Add support for creating network interfaces for ports using the Broadcom KNET driver instead of TAP interfaces.
These provide better performance and lower latency, since packets do
not need to flow through multiple (network) layers anymore, but can only
be used when running on the switch.
Since these are still experimental, and only usable on-switch, add a flag for enabling them explicitly.
These provide better performance and lower latency, since packets can be forwarded from DMA to the interfaces directly, instead of going through multiple layers of network and kernel/userspace boarders.
Running pipelines on switches.
KNET interfaces are currently assigned semi-random mac addresses (stable OUI, but offset within …
> add initial support for Broadcom KNET interfaces on switch

- src/netlink/nl_l3.cc
- src/netlink/nl_l3.h
- src/netlink/nl_l3_interfaces.h
Make sure we do not add host entries for l3 neighs for which we do not
have a route until we a route gets added, and drop the host entries
again when the route gets removed.
To do this, we need to start keeping track of all l3 neighs we currently
handle. To make this easy, use set, and reuse the nh_stub to store the
neighbor information.
To allow nh_stub to be used in a set, we need to make it comparable, so
implement the < operator for it.
Using this we can then determine the routability of a l3 neigh we add by
asking the kernel for the route to it, then checking if it has a nexthop
that exist on one of our interfaces.
Only if this is true, add a host route for it and add it to the set of
routed l3 neighbours, in all other cases add it to the set of unrouted
l3 neighbours.
Then when …
> nl_l3: only route l3 neighs if we have a route for them

- meson.build
- pkg/systemd/baseboxd.service.in
- scripts/baseboxd-knet-reset.py
Make sure that all KNET interfaces are removed after baseboxd stopped,
so restarting baseboxd (either intentional or because it crashed) does
not fail due to already existing knet interfaces.
This aligns the behaviour with how it works with the default tap
interfaces, which get removed when baseboxd closes.
The tap interfaces are removed automatically since they are owned by
baseboxd and dropped once baseboxd goes away, but this does not work for
the KNET interfaces, since they are neither owned by baseboxd, nor do
they have any facility to remove them automatically.
The proper way to fix this would be for baseboxd handle sigterm and
gracefully remove them, but the code is currently not equipped well for
that, and will require a larger rework.
As an interim smaller solution, add a python …
> add a post exit script to remove KNET interfaces

- src/netlink/nl_l3.cc
- src/utils/rofl-utils.h
RTM_GETROUTE (as done via `nl_route_query`) does not actually give us the route for a destination net, it gives us the route to a destination host, with an implicit /32 resp. /128. This works by accident for all non-default routes (since the first IP is part of the network), but falls apart for IPv4 default routes, since 0.0.0.0/32 is the any address, which aliases to localhost.
To fix this, actually ask the netlink cache for a route with the appropriate destination. As a bonus side effect, the dst of the route
will already have the correct prefix length, and we do not need to modify it anymore.
In addition, fix mask calculation for prefix length 0 on x86 by avoiding undefined behaviour.
> nl_l3: properly handle default routes

- pkg/systemd/sysconfig.template
Add the default value of the per-module GLOG flag
The GLOG_vmodule is available and useful for debugging, as it allows to set per-module log levels. The default value is 0, so we can write that into the default config file to make users aware of its existense.
The documentation on how to use it is available on the GLOG docs and soon-to-be on our docs.bisdn.de page as well.
Adding the line to the baseboxd config and restarting baseboxd works fine.
I have not run any complete pipelines
> sysconfig.template: add GLOG_vmodule default value

- src/netlink/nl_bridge.cc
Avoid a race between flow removed modifications and removing the cache
entries.
Removing the L2 entries from the switch will result in flow removed
notifications. If we are fast enough handling them, we will handle them
before we get to remove the cache entries, the flow removed handler will
try to remote the entries from the kernel. This will fail, since we may
not modify the fdb of a non-existing vlan.
To avoid even trying, we need to remove the entries from the cache
first, so we never try to remove the kernel entries.
> nl_bridge: flush cache before removing entries

- src/netlink/port_manager.h
The port_manager is an interface class. The destructor should be
implemented by whatever class inherits port_manager.
Avoids the compilation warning
```
```[3/18] Compiling C++ object baseboxd.p/src_netlink_ctapdev.cc.o
In file included from ../src/netlink/tap_manager.h:13,
from ../src/netlink/ctapdev.cc:18:
../src/netlink/port_manager.h:31:7: warning: 'class
basebox::port_manager' has virtual functions and accessible non-virtual
destructor [-Wnon-virtual-dtor]
31 | class port_manager {
|       ^~~~~~~~~~~~
```
Signed-off-by: Rubens Figueiredo <rubens.figueiredo@bisdn.de>
> port_manager: make destructor virtual

- src/netlink/cnetlink.cc
We need to check the family of the passed cache object, not the
argument. Else we read random garbage from the stack, and sometimes it
might or might not be equal to AF_INET6.
Fixes get_link_by_ifindex sometimes failing to find a link object, which
may even crash baseboxd:
```
Jul 07 23:31:22 accton-as4610 baseboxd[1121]: I0707 23:31:22.864306  1129 cnetlink.cc:679] is_bridge_interface: vlan ok
Jul 07 23:31:22 accton-as4610 baseboxd[1121]: baseboxd: ../git/src/netlink/cnetlink.cc:660: bool basebox::cnetlink::is_bridge_interface(rtnl_link*) const: Assertion `l' failed.
Jul 07 23:31:22 accton-as4610 systemd[1]: Created slice system-systemd\x2dcoredump.slice.
Jul 07 23:31:22 accton-as4610 systemd[1]: Started Process Core Dump (PID 1741/UID 0).
```
Fixes: 50fe194b8f79 ("cnetlink: fetch bridge …
> cnetlink: get_link_by_ifindex: fix af family check

- .github/workflows/linter.yml
- src/netlink/knet_manager.cc
- src/netlink/nl_l3_interfaces.h
- src/of-dpa/controller.cc
This project uses the .clang-format in this repo, with only a few recent commits not following the policy.
Changes created with:
find . -name '*.cc' -o -name '*.h' | xargs clang-format -style=file -i
To prevent further regressions, enable the super-linter in the CI for this repo.
> Update source files for clang-format and add super-linter

- src/netlink/cnetlink.cc
- src/netlink/nl_l3.cc
properly ignore AF_INET6 link objects in libnl 3.6+ that otherwise cause unexpected behavior in baseboxd.
libnl 3.6.0 introduced listening for IPv6 configuration changes on links. Due to the design of libnl, these are tracked as additional link objects in the cache with the address family AF_INET6, and they only contain basic link information in addition to the IPv6 configuration.
These can easily show up when using rtnl_link_get(ifindex), which is also used internally by rtnl_addr_get_link(). These incomplete link objects then cannot be properly handled by baseboxd, so we need to make sure to get the right objects from the cache (AF_UNSPEC/AF_BRIDGE).
Running a pipeline with this change and libnl 3.7, and having seen no failures related to this anymore.
> properly ignore AF_INET6 link objects in libnl 3.6+

- src/netlink/cnetlink.cc
- src/netlink/nl_vlan.cc
- src/netlink/nl_vlan.h
Apply any required vlans to ports on detachment to allow configured IP configuration to work again..
Attaching a port to a bridge will remove its internal vlan configuration, so that the bridge vlans will take precedence. On detachment, the configured bridge vlans get removed, but the original vlan configuration is not restored. This can cause IP addresses configured on the port to stop working.
This is not a complete fix, as instead of replacing the normal (reference) counted vlan configuration the bridge should also make use of it (and taking/dropping references for all vlans). Also any IP addresses configuration changes while attached to a bridge will also lead to a potentially broken state.
Running a pipeline with the changes applied, and configuring an ip address to a port, attaching …
> restore vlan configuration when detaching port from bridge

- src/netlink/nl_bridge.cc
When deleting a VLAN from an stp bridge, set the port state to BR_STATE_FORWARDING
When removing a VLAN from a bridged port, we currently set its STP state to DISABLED, dropping all traffic on it. When the port then gets removed from the bridge, the VLAN will continue being blocked on this port. To ensure this does not happen, use FORWARDING as the default state. The VLAN flow/group memberships will still take care of filtering the traffic while being a bridge member, so this is fine to do.
This follows a change we did in creation of STG groups, where we switched the default from DISABLED to FORWARDING.
This was tested with our latest testing images, including the latest stg fixes in meta-ofdpa
This was run on the agema-ag7648, but will extend to all our supported platforms.
edit: updated …
> nl_bridge: default stp state should be forwarding

- pkg/systemd/sysconfig.template
- src/baseboxd.cc
KNET interfaces on switch work stable, and offer more throughput and
lower latency, and avoid the issue of traffic to/from controller
overloading the OpenFlow connection.
So switch to them as default and drop the experimental tag.
> enable KNET interfaces by default 

- pkg/systemd/sysconfig.template
- src/baseboxd.cc
- src/netlink/cnetlink.cc
- src/netlink/knet_manager.cc
- src/netlink/knet_manager.h
- src/netlink/port_manager.h
- src/netlink/tap_manager.cc
- src/netlink/tap_manager.h
Linux will flood/forward any packets it sees on a bridge by default. This can lead to packet duplication if the packet was already forwarded/flooded by the ASIC. This can be avoided by marking packets as forwarding being offloaded, so tell KNET to mark any received packets as such.
To allow disabling it in case of unexpected side effects, add a flag for controlling the behavior.
The implementation is kept as generic as possible, in case we ever implement it for TAP interfaces as well.
> mark packets as offloaded when using KNET

- src/netlink/cnetlink.cc
- src/netlink/knet_manager.cc
- src/netlink/port_manager.h
- src/netlink/tap_manager.cc
- src/of-dpa/controller.cc
- src/of-dpa/controller.h
- src/sai.h
Propagate admin state/config of physical ports to the hardware via port_mod messages.
OpenFlow expects the mac address of the port according to the port table in the message, so store it when registering a port, and use it regardless of the current mac address of the port.
To have a defined initial state, set all newly registered ports as down. This avoid having to modify OF-DPA default, but may cause ports to be up for a short time until baseboxd initialized the ports.
> cnetlink: propagate admin port config

- src/netlink/nl_route_query.h
When there is no route for a host, the kernel may respond with an error, which we treat as fatal and crash. Fix this by accepting the error as normal.
When there is no default route, the kernel may respond with -ENETUNREACH or -EHOSTUNREACH instead of a route. libnl then translates this error as -NLE_FAILURE, so treat -NLE_FAILURE as no route found and just return a nullptr.
We should not crash when failing lookups because the management interface is (temporarily) down.
Ran a pipeline on as4630-54pe, which succeeded.
> properly handle route lookups when no default route

- src/netlink/cnetlink.h
- src/netlink/nl_bond.cc
- src/netlink/nl_bridge.cc
- src/netlink/nl_bridge.h
The kernel will set ports to disabled while the bridge interface is down to inhibit forwarding regardless wether STP is enabled for the bridge, and we should be doing the same.
So do not ignore port STP state changes when STP is disabled.
Fixes: ee54b7ae49d2 ("nl_bridge: implement tracking global and pervlan stp state;       * adds struct to track g/pv stp states;         * adds setting of stp state in the ASIC")
see above
Bridges while down should not allow communication between ports at all.
Pinging between hosts via switch, once with the bridge interface down, once up (e.g. vlan-bridge test).
Before pinging succeeds always regardless of admin state of bridge, after only if the bridge is up.
> nl_bridge: always set port stp state

- pkg/systemd/sysconfig.template
- src/baseboxd.cc
- src/netlink/cnetlink.cc
- src/netlink/knet_manager.cc
- src/netlink/knet_manager.h
- src/netlink/port_manager.h
- src/netlink/tap_manager.cc
- src/netlink/tap_manager.h
- src/of-dpa/controller.cc
- src/of-dpa/controller.h
- src/sai.h
Meta PR for collecting all changes for baseboxd 2.0
Contains:
* Mark KNET as stable, and use it by default
* mark packets as offloaded so bridge won't duplicate them
* propagate admin state of ports to ASIC
> Baseboxd 2.0

- src/netlink/nl_bridge.cc
The bridge may contain other interfaces than port and bond interfaces, like vxlan interfaces, so we need to make sure that we have a valid port_id before trying to assign STP state.
Silences errors like:
Mar 21 21:56:10 delta-ag7648 kernel: swbridge: port 2(vxlan50000) entered forwarding state
Mar 21 21:56:10 delta-ag7648 baseboxd[1169]: I20230321 21:56:10.493907  1331 nl_bridge.cc:227] update_interface STP state changed, old=0 new=3
Mar 21 21:56:10 delta-ag7648 ofdpa[1197]:
Mar 21 21:56:10 delta-ag7648 ofdpa[1197]:
Mar 21 21:56:10 delta-ag7648 ofdpa[1197]:
Mar 21 21:56:10 delta-ag7648 ofdpa[1197]: Usage (STG): Usages:
Mar 21 21:56:10 delta-ag7648 ofdpa[1197]:           stg create [<id>]            - Create a STG; optionally specify ID
Mar 21 21:56:10 delta-ag7648 ofdpa[1197]: …
> nl_bridge: do not try to set stp states on non-port interfaces

- src/netlink/cnetlink.cc
Improve VxLAN setup and handle various orders of operations (again) that got broken with https://github.com/bisdn/basebox/commit/935d0e6fbd9a958a32189638be78ff5fbc7a2cc4.
Fix VxLAN setup handling by properly notifying the bridge about VxLAN attachement again, and don't try to call `vxlan::create_endpoint()` twice for late attachment / VxLAN creation.
Fixes various VxLAN setup failures, and potentially random instability in tests.
Ran the testing pipeline on as4630-54pe, with all tests green.
> VxLAN stability fixes

- src/netlink/cnetlink.cc
- src/netlink/cnetlink.h
- src/netlink/nbi_impl.cc
- src/netlink/nbi_impl.h
- src/of-dpa/controller.cc
- src/sai.h
Fix handling of IP addresses on the lo interfaces added before baseboxd was started.
baseboxd scans for ip addresses on the lo interface on startup, since we won't be getting notifications about them if they were added before libnl was enabled.
Unfortunately this scan is being done potentially before the OpenFlow connection is up, so adding flows will (not quite so silently) fail, and subsequently the IP address handing is broken for those addresses.
Fix this by deferring the scan until the OpenFlow connection is established.
As a side effect this fixes the EVPN test, as here addresses were configured on lo via systemd-networkd, triggering the defect.
It breaks stuff.
Running the (currently allowed to fail) evpn-ipv4 test. Without it, it fails early due to missing flows, with the fix it …
> fix initial l3 address scan of lo interface

- src/netlink/nbi_impl.cc
On the very first port event after establishing the OpenFlow connection, a port event with PORT_EVENT_ADD will be sent for all ports.
If this happens before we sent out and receive our port table reply, we will have started setting ports down since 7886f8b56c20 ("cnetlink: initialize new ports to down").
This will cause a race between ports going down and potentially subsequent port up events when e.g. systemd-networkd sets the port up again, and the generation of the port table reply.
This can result in the port table reply to contain outdated state info, which then may be processed after the latest PORT_EVENT_MODIFY event:
Aug 29 10:34:07 accton-as4610-54 baseboxd[1057]: I20230829 10:34:07.689479  1086 nbi_impl.cc:67] port_notification: PORT_EVENT_ADD: port2 status=up
Aug 29 10:34:12 …
> nbi_impl: do not apply port state from PORT_EVENT_ADD

- src/netlink/nbi_impl.cc
- src/of-dpa/controller.cc
- src/sai.h
Make sure that the link state of ports matches the state after the first port event from OF-DPA.
https://github.com/bisdn/basebox/pull/412 tried to fix the startup race between the port desc reply and the first link state event. While the solution fixed the case where the link state event was first, it broke the case where the first link state comes in after the port desc reply, as it now was ignored as the very first link state change event is sent as `PORT_STATE_NEW`.
To fix this properly, introduce a new (internal) event type `PORT_EVENT_TABLE` to mark the reply, and use this for port creation, and then treat `PORT_STATE_NEW` and `PORT_STATE_MODIFY` as the same, and let them only update state.
Fixes link states changes being lost on start up.
Run a pipeline on as4610.
> fix port state race properly

- src/netlink/nl_bridge.cc
Properly handle L2 neighbors moving between ports without corrupting the cache.
Due to bad assumptions, the code handling L2 neighbors moving between ports corrupts the local neighbor cache, poentially breaking additional moves or maybe even timouts.
1. When updating the port, updating the cache fails as the new entry is considered identical.
2. subsequently when moving to the original port back we think we already have a flow, and don't update it again.
3. `nl_bridge::fdb_timeout()` does not check the port of the returned entry from the cache, potentially deleting the wrong neighbor.
Fix both issues to allow proper updating of flows when L2 neighbors move between ports.
Extending the neighbor moving test to move twice, which then fails.
> nl_bridge: properly handle L2 neighbors moving between ports

- src/netlink/nl_l3.cc
Ignore duplicate routes installed by FRR to not break networking.
OSPF from FRR 9.0 will sometimes install a duplicate route to an on-link
route, then delete it shortly after:
```
Oct 04 08:50:41 accton-as5835-54x baseboxd[2145]: I20231004 08:50:41.874454  2171 cnetlink.cc:1223] route_route_apply: new route (nl_obj=0x7fa654022370) inet 10.0.0.0/24 table main type unicast
Oct 04 08:50:41 accton-as5835-54x baseboxd[2145]:     preferred-src 10.0.0.1 scope link priority 0 protocol kernel
Oct 04 08:50:41 accton-as5835-54x baseboxd[2145]:     nexthop dev port54 <>
...
Oct 04 08:50:42 accton-as5835-54x baseboxd[2145]: I20231004 08:50:42.178130  2171 cnetlink.cc:1223] route_route_apply: new route (nl_obj=0x7fa654022c30) inet 10.0.0.0/24 table main type unicast
Oct 04 08:50:42 accton-as5835-54x …
```
> nl_l3: ignore duplicated link routes from FRR

- src/netlink/cnetlink.cc
- src/netlink/cnetlink.h
Ignore bridges with unsupported configuration instead of treating it as fatal state and crashing.
Ignore bridges with unsupported configuration instead of treating it as fatal state and crashing. Do this by keeping a list of ignored bridges, and ignoring them for attach/detatchment until the bridges get deleted.
This avoid baseboxd getting in a broken state, as we won't apply any configuration from these bridges.
This avoids getting in an invalid OF-DPA state requiring a reboot to recover, and potentially going into a crash loop.
create a non vlan-aware bridge, see if attaching a port gets ignored
create a vlan aware bridge, see if attaching a port is processed
create a second vlan aware bridge, see if attaching a different port is ignored
> cnetlink: just ignore bridges with unsupported configuration

- src/netlink/nl_l3.cc
For IPv6LL neighbors we don't add a host entry, so we never call a function that returns an error code, keeping rv initialized.
Fix this by setting rv to 0 to restore the old behaviour before 55fe0693eaee ("nl_l3: notify routes about IPv6 link local nexthops").
Found by cppcheck:
```
src/netlink/nl_l3.cc:796:10: warning: Uninitialized variable: rv [uninitvar]
return rv;
^
src/netlink/nl_l3.cc:733:7: note: Assuming condition is false
if (add_host_entry) {
^
src/netlink/nl_l3.cc:796:10: note: Uninitialized variable: rv
return rv;
^
```
Fixes: 55fe0693eaee ("nl_l3: notify routes about IPv6 link local nexthops")
> nl_l3::add_l3_neigh(): fix potentially random return value

- src/netlink/cnetlink.cc
- src/netlink/knet_manager.cc
- src/netlink/netlink-utils.cc
- src/netlink/nl_bond.cc
- src/netlink/nl_bridge.cc
- src/netlink/nl_l3.cc
- src/netlink/nl_output.h
- src/netlink/nl_vlan.cc
- src/netlink/nl_vxlan.cc
Provide appropriate ``operator<<``s for various `rtnl_*` structs instead of forcing callers to `OBJ_CAST()` them, and drop `OBJ_CAST()` from all users.
For some netlink structs we have a `operator<<`, for others these must be cast to `nl_object *` via `OBJ_CAST()`. This makes this error prone, as one might forget to hast (which then causes just he object's address to be printed, or add a `OBJ_CAST()` when one isn't needed, which may even cause crashes if the cast object isn't a `nl_object` (e.g. `nl_addr`).
So handle this casting via appropriate `operator<<`s, and reduce the possibilities of errors.
Built and run tested with debugging enabled.
> drop the need for OBJ_CAST() when logging netlink objects

- src/netlink/nl_l3.cc
- src/netlink/nl_route_query.h
By default the kernel replies with an artifical host route when using `RTM_GETROUTE`. This means that comparing the route's dst with prefix will never be identical, unless the route added is a host route as well. To get the actual route in the kernel, we need to pass `RTM_F_FIB_MATCH` in the flags. This makes it return the full route including protocol and priority.
Difference via ip:
```
$ ip route get to 172.16.103.1
172.16.103.1 dev enp2s0 src 172.16.103.202 uid 1000 
cache 
$ ip route get fibmatch to 172.16.103.1
172.16.103.0/24 dev enp2s0 proto kernel scope link src 172.16.103.202 metric 100 
```
Fixes: https://github.com/bisdn/basebox/commit/96e14a879fde8a24350f35c55ff9b286c9503eac ("nl_l3: ignore duplicated link routes from FRR")
> fix duplicate route check for FRR

- src/netlink/nl_bridge.cc
We already assume that `rtnl_link_bridge_get_port_vlan()` may return a `nullptr` for regular bridge vlan updates, so we should do the same when calling `nl_bridge::update_vlans()` for bond attachment.
Therefore move the `empty_br_vlan` replacement to after the bond attachment special case, to ensure `old_br_vlan` and `new_br_vlan` are always valid.
Fixes a crash observed where `rtnl_link_bridge_get_port_vlan()` returned a `nullptr` for the parent bond interface, causing
`nl_bridge::br_vlan_equal()` asserts that both arguments are valid to trigger.
Reported-by: Jan Klare <jan.klare@bisdn.de>
> nl_bridge: assume bonds may have nullptr bridge vlans as well

- pkg/systemd/sysconfig.template
- src/baseboxd.cc
- src/of-dpa/controller.cc
- src/of-dpa/ofdpa_client.cc
- src/of-dpa/ofdpa_client.h
To ensure that the baseboxd and switch state are in sync, reset the switch state on connect:
* delete all flows
* delete all groups
* delete all tunnels and their tenents and nexthops
* delete all bond ports
* reset STG groups to default (all vlans in group 1)
This ensures that the we have a valid state if baseboxd was restarted, either voluntarily (due to a restart) or involuntarily (due to a crash).
> of-dpa: reset switch state on connect

- src/netlink/tap_manager.cc
Recently the kernel replaced deprecated zero-length arrays with proper flexible arrays [1]. Unfortunately this causes the compilation to fail, since now G++ rejects anything in structs behind the flexible array member:
```
Feb 16 11:42:33 | In file included from ../git/src/netlink/tap_manager.cc:11: Feb 16 11:42:33 | /tmp/generic-x86-64/work/corei7-64-poky-linux/baseboxd/2.1.0-r0/recipe-sysroot/usr/include/linux/ethtool.h: In member function 'virtual int basebox::tap_manager::set_port_speed(std::string, uint32_t, uint8_t)': Feb 16 11:42:33 | /tmp/generic-x86-64/work/corei7-64-poky-linux/baseboxd/2.1.0-r0/recipe-sysroot/usr/include/linux/ethtool.h:2199:17: error: flexible array member 'ethtool_link_settings::link_mode_masks' not at end of 'struct …
```
> tap_manager: work around flexible array members in uapi

- src/netlink/ctapdev.cc
Since linux 6.0 it is possible to create tap devices with the carrier off instead of needing to set it off after creation [1].
This prevents a race between bring up and setting the carrier off.
[1] https://github.com/torvalds/linux/commit/195624d9c26b64c6856863da30ec578a790feec4
> ctapdev: create tap devices with carrier off

- src/netlink/nl_bridge.cc
When fixing moving neighbors between ports we removed the ifindex from the filter neigh to find a neighbor at any port with the mac address.
But since we use the same neigh to construct the fdb delete message, this caused the message to miss the ifindex, and the kernel was rejecting the deletion. This resulting in us not updating out local cache of known layer 2 neighbors, and failing to relearn them.
Fix this by just using the found entry from our local cache, n_lookup.
Fixes: a566d4caa1b0 ("nl_bridge::fdb_timeout(): check ifindex of hit before deletion")
1. Let the bridge learn a neighbor
2. wait for the neighbor to timeout (after 300 seconds)
3. check with bridge fdb show wether the neighbor still exists
expected behavior: neighbor is removed from fdb
actual behavior: neighbor is still …
> nl_bridge: fix removing aged out neighbors from fdb

- src/netlink/cnetlink.cc
We don't need to check for vlan_filtering being enabled every time we attach a port to the bridge, only on the first attachement of a port to the bridge.
We don't handle vlan_filtering state changes, so even if it was disabled later, we wouldn't be able to do anything about it. So let's only check the state once when populating cnetlink::bridge.
Fixes: f93b9b54f161 ("cnetlink: just ignore bridges with unsupported configuration")
> cnetlink: only check bridge for vlan_filtering on creation

- src/netlink/nl_l3_interfaces.h
According to [1], std::set requires a Compare function that has strict weak ordering [2], but the current implementation violates the second requirement:
* If `comp(a, b) == true` then `comp(b, a) == false`.
E.g. given the nh_stubs a = <169.254.0.1,62> and b = <172.16.111.1,4>:
* `comp(a, b) == true`, as 172.16.111.1 isn't < 169.254.0.1, but 4 < 62
* `comp(b, a) == true`, as 169.254.0.1 < 172.16.111.1.
This breaks e.g. lookups in sets, causing element not being deleted or being found.
Fix this by comparing the ifindex only if the addresses are equal, not only if the other one's is larger.
[1] https://en.cppreference.com/w/cpp/container/set
[2] https://en.cppreference.com/w/cpp/named_req/Compare
Fixes: 0fdba0d69587 ("nl_l3: only route l3 neighs if we have a route for them")
> nl_l3: fix nh_stub::operator<() strict weak ordering

- src/netlink/nl_l3.cc
- src/netlink/nl_l3_interfaces.h
Properly unsubscribe from nh (un)reachable notifications:
1. make sure we only try to remove the nexthop reachable notification for this route.
2. remove nh unreachable notifications for all reachable nexthops
> nl_l3::del_l3_unicast_route() fix unsubscribing from nh notifications

- pkg/systemd/sysconfig.template
- src/baseboxd.cc
- src/netlink/nl_bond.cc
- src/netlink/nl_l3.cc
- src/netlink/nl_vlan.cc
- src/netlink/nl_vlan.h
- src/netlink/nl_vxlan.cc
Using unbridged, untagged ports at the same time as VID 1 as default PVID on a bridge may cause unexpected leakage and forwarding of traffic.
Moving to the reserved VID 4095 would avoid this, but we cannot unconditionally use it until we solved #414, as otherwise we would leak packets with VID 4095.
So for now allow changing the VID used internally for ports, but keep the default at 1.
> allow configuring the default untagged VLAN for ports

- pkg/systemd/sysconfig.template
- src/baseboxd.cc
- src/netlink/cnetlink.cc
- src/netlink/nl_bond.cc
- src/netlink/nl_bridge.cc
- src/netlink/nl_l3.cc
- src/netlink/nl_l3_interfaces.h
- src/netlink/nl_vlan.cc
- src/netlink/nl_vlan.h
- src/netlink/nl_vxlan.cc
- src/netlink/tap_manager.cc
In preparation of a BISDN Linux 5.1.1 maintenance release, create a baseboxd 2.0 release with fixes, but no new features.
The untagged internal VLAN flag I deemed as a fix, as it allows working around a known issue, and does not change behavior by default.
> 2.0.x: backport fixes from main

- meson.build
- src/netlink/cnetlink.cc
- src/netlink/knet_manager.cc
- src/netlink/nl_bond.cc
- src/netlink/nl_bridge.cc
- src/netlink/nl_l3.cc
Warnings are important and should be addressed, so make sure they cannot be ignored by enabling -Werror after fixing all warnings.
No functional changes.
> fix warnings and enable -Werror

- src/netlink/nl_l3.cc
Fix two issues when handling ip neighbours and their routability:
1. The check for routability was wrong, and was looking for a route with a nexthop (with ip). We actually want the opposite, a route without any nexthops with ip. So use `rtnl_route_guess_scope()` for that, which will tell us if this is this kind of route.
2. When marking ip neighbours as (un-)routable on route changes, we only need and should do that for on-link routes, and not any route. Without this, we may accidentally mark l3 neighs as routable if a route with the appropriate dst is added, but that isn't a on-link route (e.g. a default route).
> fix handling of neighs regarding their routability

- src/netlink/cnetlink.cc
- src/netlink/nl_bridge.cc
- src/netlink/nl_bridge.h
With a recent fix, libnl will now send the updated object instead of the update as new for callback_v2(). Unfortunately the mdb code relied on getting incremental updates as new, so this change broke mdb handling.
To fix this, rework the mdb handling the following:
1. convert all entries of old and new into separate, ordered sets
2. for any entry in the old, but not new leave the group
3. for any entry in the new, but not old join the group
This with empty sets for old respective new this can also be used new and delete of the object.
> adapt mdb handling to fixed upstream working

- src/netlink/nl_l3.cc
Fix a few issues around number of nexthops handling:
- we rejected/ignored routes with 0 nexthops (`nnhs` = 0) on add, but don't do so in removal (though I'm not convinced this is an actual thing that can happen)
- later on we assume `nnhs` = 0 means no reachable(?) nexthop yet, but we already rejected routes with `nnhs` = 0 earlier, so this can't happen! Instead, check if `l3_interfaces` is empty
- when removing a route, don't use the amount of `l3_interfaces` to determine if this is a ECMP route, but use `nnhs` instead
> nl_l3: fix nnhs handling a bit

- src/netlink/cnetlink.cc
Libnl ops that support updating objects may modify the object, even if we haven't handled the notification yet, causing older stored notifications to use an object "from the future".
Avoid this by cloning the new object. Both nl_object_clone() and nl_object_put() are NULL-safe, so we don't need to do any nullptr checks.
> cnetlink: clone objects to ensure they are unchanged

- src/netlink/cnetlink.cc
- src/netlink/cnetlink.h
- src/netlink/nl_l3.cc
- src/netlink/nl_l3.h
- src/netlink/nl_l3_interfaces.h
- src/netlink/nl_vxlan.cc
- src/netlink/nl_vxlan.h
- src/of-dpa/controller.cc
- src/of-dpa/controller.h
- src/sai.h
Implement ECMP route handling:
The current ECMP route handling implementation has seveal drawbacks:
* it assumes that all nexthops are reachable
* it does not handle nexthops becoming (un)reachable
* it uses a `set<l3_interface_id>` to ecmp group id, so if nexthops change their availability during route updates, ecmp groups may become orphaned
* it does not recycle ecmp group ids, so eventually it runs out
Fix this by implementing a `set<nh_stub>` to ecmp group id matching, for stable groups regardless of reachability of nexthops, and make `nl_l3::nh_{un}reachable_notification()` update ecmp routes, and not just mark them as (un)routable.
Finally, change the ECMP group id creation/destruction and id allocation being done in `of-dpa::controller`, like we already do for l3 interface ids, …
> implement proper ECMP route handling

- meson.build
Instead of hardcoding the systemd unit path, extract it via a systemd dependency.
> meson.build: properly get systemd unit path

- src/of-dpa/controller.cc
`controller::handle_bridging_table_rm()` will be called for various reasons, but we actually only care for one, the idle timeout.
Especially we don't care about flows being removed which we deleted ourselves, so ignore any that aren't idle timeouts.
This avoid us trying to handle flows removals we initiated, or having to detect them.
Fixes: 291591d6f313 ("l2 aging added")
> of-dpa: only notify about idle timed out bridging table flows

- meson.build
- src/netlink/nl_bridge.cc
- src/netlink/nl_fdb_flush.h
The kernel refuses to remove fdb entries for VLANs that are not configured, but at the same time won't remove permanent entries on VLAN deletion, including extern_learn entries.
Fortunately recent kernels gained the ability for bulk deletion, so add a new helper to send a flush of all extern_learn entries from a deleted vlan from a certain port.
Using this, we can make sure no entries are left behind in the removed vlan.
Any removed entry will trigger a DEL_NEIGH message from the kernel, but since we already removed the neigh from the cache and removed the flow, we do not need to handle it again here, so add a check before attempting to handle the deleted neigh.
This was tested via:
on switch:
```
$ ip link add swbridge type bridge vlan_filtering 1 vlan_default_pvid 0 $ ip link set dev …
```
> nl_bridge: flush our fdb entries on vlan removal

- src/netlink/nl_l3.cc
In add_l3_neigh_egress() we add a VLAN (reference), but we never remove it in del_l3_neigh_egress(). This creates a reference imbalance, and causes the vlan to be never deleted once there was a neighbor on an interface.
Fix this by removing the VLAN on neigh removal as well.
> nl_l3::del_l3_neigh_egress(): remove created VLAN as well

- src/netlink/nbi_impl.cc
Link speed/duplex changes do not trigger any notifications, only link state changes do. Therefore we need to make sure that speed/duplex is set correctly before setting the link state to up for ports.
When setting the link state first, it leaves a window where a process reacting to the link state event may read out old speed/duplex before we had a change to update them, and the default speed/duplex is 10mbit/half for TAP.
This can for example lead to breakage in LACP, where it uses the link speed to calculate the actor key. If it uses the wrong/old speed, it calculates a different key than the other side, and LACP will then fail to synchronize, breaking the link.
So make sure to set the speed and duplex first on link up, and reverse on link down.
Fixes: b5fe46ca64d4 ("tap_manager: set …
> nbi_impl: set speed/duplex before setting link up

- src/netlink/nl_l3.cc
Use nl_l3::add_l3_neigh_egress() in nl_l3::add_l3_unicast_route() instead of open coding it.
This changes the ifindex of the nh notification, but that aligns with all other places using it:
- nl_l3::del_l3_unicast_route() uses ifindex of the neigh
- nh_{un}reachable_notification() uses ifindex of the neigh for matching
This also fixes an add/remove vlan imbalance between add_l3_unicast_route() and del_l3_unicast_route() for nexthops, as del_l3_unicast_route() is using del_l3_neigh(), which removes the vlan, but the open coded add in add_l3_unicast_route() does not add one.
(cherry picked from commit 200eba451c7c2bbece0efd8043c7e5a8ffa404a8)
Fixes: 3a96b2def21a ("nl_l3::del_l3_neigh_egress(): remove created VLAN as well")
> 1.x: nl_l3: use add_l3_neigh_egress() instead of open coding it

- src/netlink/nl_l3.cc
nl_l3::add_l3_neigh_egress()'s signature sets nullptr as the default value for vrf_id, but later accesses it unconditionally.
Fix this by only setting it if set.
Fixes: 7788e2d82804 ("feat: enable IP addressses on Bridge Virtual Interfaces; enable multiple creation of VRF interfaces and attachement of BVI to these interfaces; example script for configuration of the VRFs")
Fixes: 9db220e5c0bf ("nl_l3: use add_l3_neigh_egress() instead of open coding it")
(cherry picked from commit 0157c07e1f875805c05da404b927170d274a37c3)
> 1.x: nl_l3::add_l3_neigh_egress(): handle vrf_id as nullptr

- src/netlink/tap_io.cc
When accepting a packet, we may copy more than was allocated:
size_t len = sizeof(std::size_t) + 22 + td->mtu;
...
auto *pkt = (packet *)std::malloc(len);
pkt->len = read(fd, pkt->data, len);
^^^^^^^^^^^^^^
pkt->data is at an offset of pkt, but len is the size of the whole struct. So read() may write up to sizeof(pkt->len) over the end of the allocated pkt struct.
Fix this by reducing the maximum read size by size of pkt->len.
Found via valgrind:
valgrind[1714]: ==1714== Thread 3:
valgrind[1714]: ==1714== Syscall param read(buf) points to unaddressable byte(s)
valgrind[1714]: ==1714==    at 0x625E22C: __libc_read (read.c:26)
valgrind[1714]: ==1714==    by 0x625E22C: read (read.c:24)
valgrind[1714]: ==1714==    by 0x278652: read (unistd.h:38)
valgrind[1714]: ==1714==    by 0x278652: …
> tap_io::handle_read_event(): fix potential buffer overrun

- src/netlink/cnetlink.cc
- src/netlink/nbi_impl.cc
- src/netlink/nl_bridge.cc
- src/netlink/nl_bridge.h
- src/of-dpa/controller.cc
- src/of-dpa/controller.h
- src/of-dpa/ofdpa_client.cc
- src/of-dpa/ofdpa_client.h
- src/sai.h
Add support for the `LOCKED` flag of switch ports and fdb entries:
* `LOCKED` ports do not learn and do not forward packets from unknown mac addresses, so disable learning and forwarding for them.
* `LOCKED` fdb entries are not used for forwarding, but mark a mac address as "seen" on a port. Since this is basically like they weren't learnt, ignore these entries and only add them to OF-DPA once they lose their `LOCKED` flag.
To be able to do so, we need to enhance OF-DPA with the ability to do fine grained learning configuration. Since OF-DPA is old, model the internal interface after SAI [1], with a two modifications:
* add a mode that corresponds to what we currently use, where we log and forward
* add a method for configuring learning behavior for source port violations (i.e. a neighbor …
> add support for locked bridge ports and locked fdb entries

- src/netlink/tap_manager.cc
Recently the kernel replaced deprecated zero-length arrays with proper flexible arrays [1]. Unfortunately this causes the compilation to fail, since now G++ rejects anything in structs behind the flexible array member:
```
Feb 16 11:42:33 | In file included from ../git/src/netlink/tap_manager.cc:11: Feb 16 11:42:33 | /tmp/generic-x86-64/work/corei7-64-poky-linux/baseboxd/2.1.0-r0/recipe-sysroot/usr/include/linux/ethtool.h: In member function 'virtual int basebox::tap_manager::set_port_speed(std::string, uint32_t, uint8_t)': Feb 16 11:42:33 | /tmp/generic-x86-64/work/corei7-64-poky-linux/baseboxd/2.1.0-r0/recipe-sysroot/usr/include/linux/ethtool.h:2199:17: error: flexible array member 'ethtool_link_settings::link_mode_masks' not at end of 'struct …
```
> 1.x: tap_manager: work around flexible array members in uapi

- src/netlink/cnetlink.cc
- src/netlink/nbi_impl.cc
- src/of-dpa/controller.cc
Fix two issues in the recently introduced port learning configuration support:
1. Fix the flags value for port_set_move_learn(), which may not correspond to the expected value else.
2. Fix racy initial port learning setup by moving the learning setup into the netlink thread, which also does all the other gRPC calls.
Especially the latter caused issues when setting up bond interfaces with systemd-networkd, as these bond setups were parallel to setting up learning, causing some bond interface calls to fail.
> fix setup learning for ports

- src/netlink/nbi_impl.cc
This is a backport of https://github.com/bisdn/basebox/pull/451.
Link speed/duplex changes do not trigger any notifications, only link state changes do. Therefore we need to make sure that speed/duplex is set correctly before setting the link state to up for ports.
When setting the link state first, it leaves a window where a process reacting to the link state event may read out old speed/duplex before we had a change to update them, and the default speed/duplex is 10mbit/half for TAP.
This can for example lead to breakage in LACP, where it uses the link speed to calculate the actor key. If it uses the wrong/old speed, it calculates a different key than the other side, and LACP will then fail to synchronize, breaking the link.
So make sure to set the speed and duplex first on link up. On …
> 1.x: nbi_impl: set speed/duplex before setting link up

- Makefile
Fix and extend the make targets for bumping the version:
1. fix major version bumps to reset the minor version to 0
2. always include the patchver, even when 0 to match existing release versions
3. add a new patchversion bump make target (e.g. 2.3.1 -> 2.3.2)
4. ensure a version bump commit only includes a VERSION file change
5. also sign the version bump commit (which we enforce for the tag as well)
> fix and extend the bumpversion* make targets

- meson.build
meson complains that when searching for libs, you should omit the libprefix:
```
Run-time dependency libgflags found: NO (tried pkgconfig and cmake)
WARNING: find_library('libgflags') starting in "lib" only works by accident and is not portable
Library libgflags found: YES
```
So fix this by dropping the lib prefix from any cppc.find_library() calls.
The fact that we even landed here also showed that the initial dependency() name was wrong, so fix both glog and gflags, which do not have a lib prefix for their dependency names.
This is not true for libnl and libsystemd though, they still need the lib prefix for looking them up as a dependency.
After:
```
Run-time dependency gflags found: YES 2.2.2
...
Run-time dependency glog found: YES 0.7.1
```
> meson.build: fix finding libs

- src/netlink/cnetlink.cc
- src/netlink/nbi_impl.cc
- src/netlink/nl_bridge.cc
- src/netlink/nl_bridge.h
- src/of-dpa/controller.cc
- src/of-dpa/controller.h
- src/of-dpa/ofdpa_client.cc
- src/of-dpa/ofdpa_client.h
- src/sai.h
Backport of changes for support of locked ports and fdb entries.
Consists of backports of #457 and the follow up fix #460.
Depends on
* https://github.com/bisdn/meta-open-network-linux/pull/181
* https://github.com/bisdn/meta-bisdn-linux/pull/287
* https://github.com/bisdn/meta-ofdpa/pull/80
> 1.x: backport support for locked ports and fdb entries

- src/netlink/ctapdev.cc
close() is defined in unistd.h, so add the appropriate #include.
Fixes the following error on build with -Werror:
```
../src/netlink/ctapdev.cc: In member function ‘void basebox::ctapdev::tap_open()’: ../src/netlink/ctapdev.cc:53:5: error: ‘close’ was not declared in this scope; did you mean ‘pclose’?
53 |     close(fd);
|     ^~~~~
|     pclose
../src/netlink/ctapdev.cc: In member function ‘void basebox::ctapdev::tap_close()’:
../src/netlink/ctapdev.cc:71:12: error: ‘close’ was not declared in this scope; did you mean ‘pclose’?
71 |   int rv = close(fd);
|            ^~~~~
|            pclose
```
> ctapdev: add missing include for close()

- src/netlink/cnetlink.cc
- src/netlink/cnetlink.h
- src/netlink/nl_bond.cc
- src/netlink/nl_bridge.cc
- src/netlink/nl_bridge.h
- src/netlink/nl_vlan.cc
- src/netlink/nl_vlan.h
- src/of-dpa/controller.cc
- src/of-dpa/controller.h
- src/sai.h
Add support for wrapping traffic on a port with an additional stacked VLAN tag. This is configured by having a VLAN interface of that port as a bridge member, where the VLAN configuration of that interface is used for the stacked VLAN tag.
The general OF-DPA configuration for that is:
* On attachment of the VLAN interface to the bridge, configure an appropriate pop VLAN tag flow.
* On configuration of a VLAN for that (VLAN interface) port, add a ingress VLAN translation that translates from (VLANInterface.VID, BridgeVLAN.VID) to BridgeVLAN.VID, and an egress VLAN translation flow that translates Bridge.VLAN.VID to (VLANInterface.VID, BridgeVLAN.VID).
Since properly updating flows on bond membership changes becomes much harder with these new type of flows, rework the VLAN handling for …
> add support for wrapping traffic on a port with a stacked VLAN tag

- src/netlink/cnetlink.cc
- src/netlink/cnetlink.h
- src/netlink/netlink-utils.h
- src/netlink/nl_l3.cc
- src/netlink/nl_l3_interfaces.h
- src/netlink/nl_output.h
- src/of-dpa/controller.cc
In rare instances it can happen that a route update targeting a nexthop object in kernel gets send to userspace without any nexthop information set exept the nexthop id.
Since we currently rely on routes having this information, this breaks us applying the route, since we do not know what the actual nexthop is.
Fix this by tracking nexthop objects and using the cache as a fallback for looking up the nextop data of routes by the nexthop id.
> nl_l3: work around kernel sending routes using nhid with no nexthops

- src/netlink/cnetlink.cc
- src/netlink/cnetlink.h
Work around missing route removal notifications from kernel on link down with routes targeting nexthops on that link by forcing a cache resync on link down events to catch removed routes.
When a link goes down, the kernel will delete all nexthops on that link without sending out netlink notifications.
When a nexthop gets deleted, the kernel will delete all routes with the nexthop as destination without sending out netlink notifications.
These two combined means that when using nexthop objects, like FRR does by default, deletion of routes on link loss are never seen by libnl, and consequently never seen by baseboxd.
This causes flow table entries for routes to persist even though they were deleted in the kernel.
To work around this, `use nl_cache_resync_v2()` to trigger a resync of all …
> cnetlink: sync route cache on linkdown events

- src/netlink/cnetlink.cc
- src/netlink/cnetlink.h
Syncing routes on link down may trigger updates on link local routes due to route flag changes, but baseboxd is not prepared to handle this, and causes all l3 neighbors on that link to be treated as unroutable.
IPv6 routes with nexthops seem to behave differently than IPv4 routes, and seem to reappear silently on link up again. Since there is no notification (again) from the kernel, we miss the reappearance of the route.
Due to the amount of breakage, lets's revert this for now until we have addresses these two issues.
This reverts commit 9a58b5ddbe9e7ce65228f4bc5bcf325e6905e14c.
> Revert "cnetlink: sync route cache on linkdown events"

- src/netlink/cnetlink.cc
- src/netlink/nl_l3.cc
When attaching a VRF to or from a VLAN interface, we remove the ip addresses since we will get new address notifications for the correct new table (VRF). But routes may also already exist, and may stay in the original table. Especially on detachment, we fail to remove the routes again, so VRF assigned routes can remain.
Additionally, the IPv6 LL route check didn't consider the table, so it would fail to remove the VRF IPv6 LL route if there were other non-VRF LL routes. So make sure to match on the table as well.
Fixes https://github.com/bisdn/basebox/issues/290
Ran weekend pipelines with PR applied, no observed regressions.
To verify ran the vrf-lacp test on as4610.
After running the test:
```
accton-as4610-54:~$ client_flowtable_dump  30
Table ID 30 (Unicast Routing):   Retrieving all …
```
> properly handle existing routes on VRF attachement/detechment

- src/of-dpa/controller.cc
Make use of the newly introduced BPDU Termination MAC flows and use them instead of ACL flows for BPDU traffic.
This properly marks them as BPDUs for KNET, and prevents them from being counted as dropped.
Depends on https://github.com/bisdn/rofl-ofdpa/pull/119
> of-dpa: use termination mac instead of acl flows for BPDUs

- src/netlink/nl_bridge.cc
- src/netlink/nl_bridge.h
- src/netlink/nl_l3.cc
- src/netlink/nl_l3.h
Running valgrind, it detected we are leaking allocated `nl_addr`s at various places following the pattern:
```
auto p = nl_addr_alloc(...);
nl_addr_parse(<address>, <family>, &p);
std::unique_ptr<nl_addr, decltype(&nl_addr_put)> tm_addr(p, nl_addr_put);
```
The core issue here is that `nl_addr_parse() does its own allocation and updates `p` with a pointer to it, and thus the initial allocation behind `p is leaked.
Since we always parse static addresses, replace those dynamic allocations with statically allocated addresses in the constructor.
while fixing this, also fix the IPv6 multicast prefix from `ff80::/10` to `ff00::/8`.
> fix nl_addr leaks detected by valgrind
