- src/roflibs/netlink/ofdpa_bridge.cpp
- src/roflibs/netlink/sai.hpp
- src/roflibs/of-dpa/cbasebox.cpp
- src/roflibs/of-dpa/cbasebox.hpp
* egress vlan filtering turned on
* updated sai to pass egress vlan filtering
* add each port w/ its vlan to according L2 Flood Group
> add dlf functionality

- src/roflibs/netlink/cnetlink.cpp
FATAL will immediately exit as well
> set several log levels to be fatal

- src/baseboxd/baseboxd.cpp
- src/roflibs/netlink/Makefile.am
- src/roflibs/netlink/cnetlink.cpp
- src/roflibs/netlink/cnetlink.hpp
- src/roflibs/netlink/crtlinks.hpp
- src/roflibs/netlink/ctapdev.cpp
- src/roflibs/netlink/ctapdev.hpp
- src/roflibs/netlink/nbi_impl.cpp
- src/roflibs/netlink/nbi_impl.hpp
- src/roflibs/netlink/sai.hpp
- src/roflibs/netlink/tap_manager.cpp
- src/roflibs/netlink/tap_manager.hpp
- src/roflibs/of-dpa/cbasebox.cpp
- src/roflibs/of-dpa/cbasebox.hpp
* remove tap_manager from cbasebox
* add enqueue functions to sai and implement them accordingly, since
tap_callback has to be removed
* new ports have to be notified via sai to be created
> refactoring of packet io

- src/baseboxd/baseboxd.cpp
- src/roflibs/netlink/cnetlink.cpp
- src/roflibs/netlink/cnetlink.hpp
- src/roflibs/netlink/nbi_impl.cpp
- src/roflibs/netlink/nbi_impl.hpp
- src/roflibs/of-dpa/cbasebox.cpp
- src/roflibs/of-dpa/cbasebox.hpp
added signal handler to support SIGINT. bugfixes to exit nice.
> handle SIGINT

- src/roflibs/netlink/cnetlink.cpp
- src/roflibs/netlink/cnetlink.hpp
- src/roflibs/netlink/nbi_impl.cpp
- src/roflibs/of-dpa/cbasebox.cpp
- src/roflibs/of-dpa/cbasebox.hpp
* handle errors emitted from fm_driver while not beeing connected
* add lock to sync dpt_close and dpt_open
> remove ports after disconnect

- src/roflibs/netlink/cnetlink.cpp
ports should only be registered on a NL_ACT_NEW event.
> fixed port registeration and typo

- src/roflibs/of-dpa/cbasebox.cpp
despite some other cleanup, the datapath id is now locally stored and
printed correctly on opening and closing connections.
> minor changes to logging output

- src/roflibs/netlink/cpacketpool.cpp
- src/roflibs/netlink/cpacketpool.hpp
- src/roflibs/netlink/ctapdev.cpp
- src/roflibs/netlink/ctapdev.hpp
- src/roflibs/netlink/nbi_impl.cpp
- src/roflibs/netlink/tap_manager.cpp
- src/roflibs/of-dpa/cbasebox.cpp
* fix tapdev read behaviour to level triggered
* packetpool and logging cleanup
* further packet io cleanup
> Improve packet io

- src/roflibs/netlink/tap_manager.cpp
> write fs should not be registered on LT epoll

- .travis.yml
- src/roflibs/netlink/tap_manager.hpp
- src/roflibs/of-dpa/cbasebox.cpp
- src/roflibs/of-dpa/cbasebox.hpp
> formatting and travis

- src/roflibs/of-dpa/cbasebox.cpp
- src/roflibs/of-dpa/cbasebox.hpp
crofbase::handle_wakeup needs to be called
> cbasebox: handle_wakeup is not used and shadows crofbase

- configure.ac
* update rofl-common dependency to 0.11.2
> update rofl-common dependency

- src/roflibs/of-dpa/cbasebox.cpp
* adapt to new rofl-ofdpa where fm & gm are returned by functions
* sending is now done by the controller
> adapt to new rofl-ofdpa

- configure.ac
* update required due to API changes
> update rofl dependencies

- src/roflibs/of-dpa/cbasebox.cpp
- src/roflibs/of-dpa/cbasebox.hpp
Periodically requests port statistics and stores the reply.
> request_stats&handle_reply

- README.md
> fix readme to setup vlan filtering on bridge

- src/netlink/cnetlink.hpp
- src/netlink/nbi_impl.cpp
- src/netlink/tap_manager.cpp
- src/of-dpa/controller.cpp
netlink: start listening by default
of-dpa controller: improved verbose logging
tap_manager: log port_id as well
cnetlink: do not throw in get_port_id
> some minor improvements

- configure.ac
- src/Makefile.am
protoc and grpc_cpp_plugin are now configurable or auto detected in PATH
> configuration or autodetection of programs

- src/netlink/tap_manager.cpp
during tap creation we still receive notifications from cnetlink. This
cannot be block since netlink messages might be dropped. fixes f1d021e
> tap_manager: do not lock during tap creation

- src/netlink/cnetlink.cpp
- src/netlink/cnetlink.hpp
to support different link types cnetlink is refactored to simplify
addition of new link types like vxlan
> support multiple devices

- src/netlink/cnetlink.cpp
- src/netlink/cnetlink.hpp
- src/netlink/tap_manager.cpp
- src/of-dpa/controller.cpp
* moved detailed logs to vlog 3
* cnetlink logs more details on vlog 3
* increased buffer size for cnetlink
* switched buffer to a vector in cnetlink
> logging updates

- src/Makefile.am
- src/netlink/cnetlink.cpp
- src/netlink/cnetlink.hpp
- src/netlink/nl_l3.cpp
- src/netlink/nl_output.cpp
- src/netlink/nl_output.hpp
* added ostream operators of netlink objects
* improved bridge slave handling
> general improvements

- src/of-dpa/controller.cpp
- src/of-dpa/controller.hpp
* clear l2_domain explicitely when dpt_closed
> clear l2_domain in case of dpt_closed

- src/of-dpa/controller.cpp
* fixes a bug where the DLF flowmod was sent when the l2 flood group has been modified (sending DLF after adding the group is sufficient)
> do not send DLF fm when l2 flood group is modified

- src/Makefile.am
- src/netlink/cnetlink.cpp
- src/netlink/cnetlink.hpp
- src/netlink/nbi_impl.cpp
- src/netlink/netlink-utils.cpp
- src/netlink/netlink-utils.hpp
- src/netlink/nl_hashing.hpp
- src/netlink/nl_l3.cpp
- src/netlink/nl_l3.hpp
- src/netlink/nl_obj.hpp
- src/of-dpa/controller.hpp
a lot of refactoring to support future vlan, vxlan and l3 improvements
> Refactoring

- src/netlink/cnetlink.cpp
- src/netlink/cnetlink.hpp
- src/netlink/nl_bridge.cpp
- src/netlink/nl_bridge.hpp
refactor and modify how bridging is handled. The major part was to simplify VLAN modifications.
> Bridging rework

- src/netlink/cnetlink.cpp
- src/netlink/cnetlink.hpp
- src/netlink/netlink-utils.cpp
- src/netlink/netlink-utils.hpp
- src/netlink/nl_l3.cpp
- src/netlink/nl_vlan.cpp
- src/of-dpa/controller.cpp
baseboxd now synchronizes the previously configured IP addresses on the loopback interface.
> Added way to sync the previously existing lo interfaces

- src/netlink/ctapdev.cpp
this fixes a -Werror=stringop-truncation
> ctapdev: set correct IFNAMSIZ length

- src/netlink/cnetlink.cpp
* Wait for netlink messages to be acked from the kernel
* minor debug log changes
> Netlink: synchronous messages to kernel

- Vagrantfile
Download latest version from the [vagrant page](https://www.vagrantup.com/downloads.html).
> fedora 28 vagrant VM

- src/netlink/nl_bridge.cpp
empty vlan handling and refactoring and cleanup
> nl_bridge: bugfix and cleanup

- src/netlink/cnetlink.cpp
in this was a warning for l2 only
> cnetlink: remove warning

- src/netlink/tap_manager.cpp
In rare cases we already get the netlink event before having the fd
registrered. This aligns the fd registration to prevent these cases.
> tap_manager: force fd registration with name registration

- meson.build
- src/netlink/cnetlink.cpp
- src/netlink/cnetlink.hpp
- src/netlink/netlink-utils.cpp
- src/netlink/netlink-utils.hpp
- src/netlink/nl_bond.cpp
- src/netlink/nl_bond.hpp
- src/netlink/nl_bridge.cpp
- src/netlink/nl_l3.cpp
- src/netlink/nl_vlan.cpp
- src/of-dpa/controller.cpp
- src/of-dpa/controller.hpp
- src/sai.hpp
* update link_type handling
* handle single bond interface
> bond: add single port bond wrapper

- src/netlink/nl_l3.cpp
some minor improvements wrt. l3 see commits for details
> l3: improvements

- meson.build
- pkg/release/rpm/baseboxd.spec.in
- pkg/testing/rpm/baseboxd.spec.envsubst
* Fix broken install path
* change installation path to usr bin
> Fix: change default installation location

- examples/README.md
- examples/bridging/01-controller
- examples/bridging/01-server
- examples/networkd/port.network
- examples/networkd/switchbr.netdev
- examples/networkd/switchbr.network
- examples/routing/IPv4/01-controller
- examples/routing/IPv4/01-server
- examples/routing/IPv6/01-controller
- examples/routing/IPv6/01-server
- examples/routing/IPv6/radvd.conf
Currently supported scripts are:
* bridging scripts
* routing scripts
* network example files
> Added examples folder for providing example setup scripts

- examples/bridging/01-controller
- examples/bridging/01-server
- examples/routing/IPv4/01-controller
- examples/routing/IPv4/01-server
- examples/routing/IPv6/01-controller
- examples/routing/IPv6/01-server
* fixes several errors in the example configuration scripts
> fix example scripts

- src/netlink/cnetlink.cpp
At least log for now when we have an overrun on the netlink
channel or we receive an invalid message
> netlink: add callbacks for overrun and invalid

- src/baseboxd.cpp
- src/netlink/nbi_impl.cpp
- src/netlink/nbi_impl.hpp
- src/netlink/tap_manager.cpp
- src/netlink/tap_manager.hpp
- src/of-dpa/controller.hpp
use shared and unique pointers
> refactor initialization

- src/netlink/cnetlink.cpp
- src/netlink/cnetlink.hpp
- src/netlink/nbi_impl.cpp
- src/netlink/nbi_impl.hpp
- src/netlink/nl_l3.cpp
- src/netlink/nl_l3.hpp
- src/of-dpa/controller.cpp
- src/sai.hpp
> Init rework

- meson.build
- src/netlink/cnetlink.cpp
- src/netlink/nl_l3.cpp
- src/netlink/nl_l3.hpp
- src/netlink/nl_l3_interfaces.hpp
* callbacks can now be registered at l3 to get notified about
routes/neighs.
* get_neighbours_of_route refactored
* minor updates to logging and comments
> l3: added notifications for routes and neighs, minor updates

- src/netlink/nl_l3.cc
* handle host route deletion
* handle v6 route deletion
* cleanup of unused code
> nl_l3: several fixups for route deletion

- src/netlink/cnetlink.cc
This change removes the auto interface up for all tap interfaces.
The background of this change is that the ifup will interfere with
network managers that try to e.g. enslave an interfaces.
> Do not ifup interfaces

- src/netlink/nl_vxlan.cc
This PR adds already configured l2 entries after the endpoint is created.
> vxlan: add existing neighbors for new endpoint

- src/netlink/nl_bridge.cc
don't take pci and dci into account
> fix vid parsing

- examples/routing/VRFs/01-controller
- src/netlink/cnetlink.cc
- src/netlink/cnetlink.h
- src/netlink/netlink-utils.cc
- src/netlink/netlink-utils.h
- src/netlink/nl_bridge.cc
- src/netlink/nl_bridge.h
- src/netlink/nl_l3.cc
- src/netlink/nl_l3.h
- src/netlink/nl_vlan.cc
- src/netlink/nl_vlan.h
- src/netlink/nl_vxlan.cc
- src/of-dpa/controller.cc
- src/of-dpa/controller.h
- src/sai.h
* Bridge VLAN interfaces are able to hold IP addresses
* enable multiple creation of VRF interfaces and attachment
of BVI to these interfaces; 
* example script for configuration of the VRFs
> VRF features in baseboxd

- .github/ISSUE_TEMPLATE.md
Add new template for correctly submitting issues directly to baseboxd.
To improve the system for parsing bugs and to better organize the project.
> doc: add issues template

- src/of-dpa/controller.cc
This PR also adds further exception handling to the functions introduced in #230, set_egress_tpid, and delete_ingress_pid.
> controller: further exception catching

- meson.build
- pkg/systemd/baseboxd.service.in
- src/netlink/cnetlink.cc
- src/of-dpa/controller.cc
> add systemd notify support

- docker/from_source/Dockerfile
> dependencies: update docker container dependencies

- src/netlink/cnetlink.cc
> Logging fix

- src/netlink/nl_l3.cc
When updating the neighbour, baseboxd must check if the neighbors state is one of:
- permanent
- noarp
- reachable
- stale
- none
- incomplete
- delay
- probe
- failed
In the case for incomplete neighbors, baseboxd must still install the rule to forward packets to the controller.
See 0a5c7c1#diff-3c368f43e25d51e19a158722ea158133R1547
See #263 
The L3 neighbor was not being updated when it moved out of the "failed" status. This PR fixes this behaviour.
-Tested with the bgp IPv6 test across two baseboxes
> neigh: fix ipv6 neigh not being updated

- src/netlink/nl_bridge.cc
Move vlan handling into nl_bridge::update_vlans so we do not need to
call it again at every calling place of update_vlans, and also can
partially handle removing vlans. Fully handling it requires further
changes.
Commands used for testing:
ip link add name bond1 type bond mode active-backup
ip link set port2 master bond1
ip link add name swbridge type bridge vlan_filtering 1
ip link set swbridge up
ip link set bond1 master swbridge
ip link set port3 master swbridge
ip link set bond1 up
ip link set port3 up
bridge vlan add vid 10 dev bond1
Before:
accton-as4610:/home/basebox# client_grouptable_dump
groupId = 0x00010002 (L2 Interface, VLAN ID = 1, Port ID = 2): duration: 27, refCount:1
bucketIndex = 0: outputPort = 2 (Physical) popVlanTag = 1 allowVlanTranslation = 0
groupId = 0x00010003 …
> nl_bridge: fix adding vlans to bonds in bridges

- src/netlink/nl_bridge.cc
> add multicast guard for include

- src/of-dpa/controller.cc
> controller: add vlog error msg

- src/netlink/cnetlink.cc
- src/netlink/nbi_impl.cc
- src/netlink/nl_bond.cc
- src/netlink/nl_bridge.cc
- src/netlink/nl_l3.cc
- src/netlink/nl_vlan.cc
- src/netlink/nl_vlan.h
- src/netlink/nl_vxlan.cc
- src/of-dpa/controller.cc
> Whitespace fix

- src/netlink/nl_l3.cc
- src/of-dpa/controller.cc
> l3: egress routing fixes

- src/netlink/cnetlink.cc
- src/netlink/cnetlink.h
- src/netlink/nl_bond.cc
- src/netlink/nl_bond.h
- src/netlink/nl_l3.cc
- src/netlink/nl_l3.h
This PR aims to merge all of the feature commits from the next branch in preparation for baseboxd 1.9.6. 
Ran nightly pipelines sucessfully.
> Merge next feature branch to release next baseboxd version

- src/netlink/nl_l3.cc
While we should not create host entries for IPv6 link local neighbors,
we still may have routes with them as the nexthop.
So we cannot early exit when handling IPv6 link local neighbors, and
still need to go through the nh_(un)reachable_callbacks and notify all
interested parties.
Since we do not add host entries, we do not need to add l3 egress
entries.
This means we might not need to drop a reference, and we cannot use
the return value anymore as an optimization on whether to notify anyone
when a nexthop gets unreachable.
Fixes forwarding of IPv6 routes through IPv6 link local neighbors.
Running the osfp-ipv6 test after the rework:
Before:
```
cel-questone-2a:~$ ip -6 route show
2001:db8::/64 dev port54 proto kernel metric 256 pref …
```
> nl_l3: notify routes about IPv6 link local nexthops

- pkg/systemd/sysconfig.template
- src/baseboxd.cc
- src/netlink/cnetlink.cc
- src/netlink/cnetlink.h
- src/netlink/nl_l3.cc
- src/netlink/nl_l3.h
- src/of-dpa/controller.cc
This PR merges all the changes in baseboxd next for release 1.9.9
> 1.9.9: merge baseboxd-next

- src/netlink/nl_l3.cc
At the point of handling a deleted l3 neighbor, it might already be
removed from the fdb, so we can't rely on it having an entry to figure
out the physical port.
In that case, traverse the map and find a match for vid/src/dst, which
should exist at this point (and only have one entry), and use that.
Fixes the following assert:
> #3  0x00007f26bdd36b32 in __assert_fail () from /lib/libc.so.6
> #4  0x000055a87d18deda in basebox::nl_l3::del_l3_neigh_egress (this=0x55a87d389cb0, n=<optimized out>) at /usr/include/c++/9.3.0/ostream:181
> #5  0x000055a87d18e7f3 in basebox::nl_l3::del_l3_neigh (this=0x55a87d389cb0, n=0x55a87d398930) at ../git/src/netlink/nl_l3.cc:920
> #6  0x000055a87d170c51 in basebox::cnetlink::route_neigh_apply (this=0x55a87d368da0, obj=...) at ../git/src/netlink/nl_obj.h:24 …
> nl_l3: handle deleting purged l3 neighbors

- src/netlink/nl_vlan.cc
Fix reference counting for vlans created for vlan interfaces, preventing clean up of vlan flows on vlan interface deletion.
The reference downcounting was broken, so we never actually tried to remove created vlans.
We should make sure that we always clean up properly behind us and don't leave any flows or groups that should not exist. Otherweise we might cause unexpected package leakage.
Create a vlan interface and delete it again, then check the flow and group tables.
```
agema-ag5648:/home/basebox# ip link add link port7 name port7.10 type vlan id 10
agema-ag5648:/home/basebox# client_flowtable_dump 10
Table ID 10 (VLAN):   Retrieving all entries. Max entries = 16384, Current entries = 1.
--  inPort = 7 (Physical)  vlanId:mask = 0x100a:0x1fff (VLAN 10) | GoTo = 20 (Termination MAC) | …
```
> fix vlan interface deletion

- pkg/systemd/sysconfig.template
- src/netlink/nl_vlan.cc
Merge changes from next into master
> Prepare for version 1.9.11

- src/netlink/cnetlink.cc
- src/netlink/netlink-utils.cc
- src/netlink/nl_bridge.cc
- src/netlink/nl_bridge.h
- src/netlink/nl_output.h
- src/of-dpa/controller.cc
- src/of-dpa/controller.h
- src/of-dpa/ofdpa_client.cc
Merges the changes from #333 , #335, #336, #337 for preparation for release 1.9.14.
> Bump version to 1.9.14

- src/netlink/nl_bridge.cc
- src/netlink/nl_l3.cc
- src/netlink/nl_vlan.cc
- src/netlink/nl_vlan.h
- src/of-dpa/controller.cc
- src/of-dpa/controller.h
- src/sai.h
Merge next into master to prepare for the next release.
Contains the following PRs:
* #345 
* #346 
* #349 
> merge next into master

- src/netlink/cnetlink.cc
- src/netlink/nl_bridge.cc
- src/of-dpa/controller.cc
- src/of-dpa/controller.h
- src/sai.h
Merge #355 and #354 for baseboxd next version
> Merge #355 and #354 for baseboxd next version

- src/netlink/nl_bridge.cc
When attaching a port to the bridge, the initial state might not
necessarily be still forwarding, the vlan might already be changed to
blocking. So we need to be sure to ask the cache for the current state.
This can especially easily happen for bond interfaces, which we ignore
until a port is attached, but it might already be attached to a bridge
(and have a stp state).
Running the bonded stp tests, which now succeed reproducably, and now run much faster, since stp is now working as expected.
Depends on https://github.com/bisdn/basebox/pull/370
> nl_bridge: fix setting initial vlan stp state

- src/netlink/cnetlink.cc
- src/netlink/cnetlink.h
- src/netlink/nl_bond.cc
- src/netlink/nl_bridge.cc
- src/of-dpa/controller.cc
- src/of-dpa/controller.h
- src/sai.h
We have accumulated quite a few style issues, so fix them to make checking new code easier.
No code changes.
> fix style check issues in various files

- src/netlink/cnetlink.cc
libnl 3.6.0 has introduced the following
https://github.com/thom311/libnl/pull/264 patch. The added group to the
dict has an effect of adding a second bridge interface entry to the cache,
refering to the inet6 link notification.
By fetching the object with the ifindex and AF_BRIDGE, we filter for the
correct object type.
Avoids the behaviour after the following instructions.
```
baseboxd up -> all ports created
ip link add swbridge type bridge vlan_filtering 1
ip link set port1 master swbridge
```
Good:
```
route_link_apply: new link bridge port1 ether 96:cf:87:84:86:23 master swbridge <broadcast,multicast>
link_created: using *bridge* bridge swbridge ether 0a:39:85:5b:25:67 <broadcast,multicast> group 0
```
Wrong:
```
link_created: using bridge *inet6* swbridge ether 0a:39:85:5b:25:67 …
```
> cnetlink: fetch bridge object with ifindex and address family

- src/netlink/cnetlink.cc
- src/netlink/nl_vxlan.cc
- src/netlink/nl_vxlan.h
nl_vxlan::init() may be called very early, before the switch connection is properly established. Any pre-existing vxlan interfaces may then cause a null pointer access when trying to create the vni, which tries to call gRPC methods.
Fix this by deferring the scan until we attach a bridge, as we support bridge attached vxlan only anways.
Avoids the following crash:
> Program terminated with signal SIGSEGV, Segmentation fault.
> #0  0x000055c68c8f49ce in basebox::ofdpa_client::ofdpaTunnelTenantCreate (this=0x0, tunnel_id=<optimized out>, vni=<optimized out>) at ../git/src/of-dpa/ofdpa_client.cc:33
> 33	  ::Status rv = stub_->ofdpaTunnelTenantCreate(&context, request, &response);
> [Current thread is 1 (LWP 2559)]
> (gdb) bt
> #0  0x000055c68c8f49ce in …
> nl_vxlan: defer vxlan scan util bridge registration

- src/of-dpa/controller.cc
Bond interfaces use a different L2 Interface group type, so we need to check for bond and handle them in controller::egress_port_vlan_remove(), like we do in controller::egress_port_vlan_add().
Fixes: c9f6de2b6f62 ("bond: expand bonding feature in baseboxd")
> controller: fix ::egress_port_vlan_remove() for bonds

- src/netlink/knet_manager.cc
- src/netlink/tap_manager.cc
Make sure to remove id_hwaddr entries on in ::portdev_destroy(), else baseboxd will crash when trying to recreate them after a OpenFlow disconnect.
Easily forcable by restarting ofagent.
Fixes the following error:
May 26 13:46:38 delta-ag7648 baseboxd[3470]: F20230526 13:46:38.699759  3485 tap_manager.cc:73] create_portdev: failed to insert hwaddr
May 26 13:46:38 delta-ag7648 baseboxd[3470]: *** Check failure stack trace: ***
May 26 13:46:38 delta-ag7648 baseboxd[3470]:     @     0x7f4c92e7804d  google::LogMessage::Fail()
May 26 13:46:38 delta-ag7648 baseboxd[3470]:     @     0x7f4c92e7a5c6  google::LogMessage::SendToLog()
May 26 13:46:38 delta-ag7648 baseboxd[3470]:     @     0x7f4c92e77b8a  google::LogMessage::Flush()
May 26 13:46:38 delta-ag7648 baseboxd[3470]:     @     0x7f4c92e7ac39 …
> {tap,knet}_manager: drop id_hwaddr entry on port removal

- src/netlink/cnetlink.cc
When a route and its nexthop (neigh) get removed at the same time, we may process the route removal before the neigh removal.
On route removal we try to unregister for nexthop notifications, and remove any pending l3 interfaces.
Since cnetlink::get_neighbour() only asks the cache, it only returns live neighs, but since the neigh was already removed from the cache, it wont find any.
At the same time, since we did not process the neigh removal yet, we are still registered for nh unreachable notifications, but since from the perspective of the nl_l3::del_l3_route(), the nexthop is already unreachable, so we fail to remove the unreachable notification.
Fix this by also going through the pending neigh deletions to find the reference in case there is a neigh delete pending.
Fixes: dfe44856fe31 …
> cnetlink::get_neighbor(): check pending notification for deleted neighs

- pkg/systemd/sysconfig.template
Added documentation for glog library:
- Log levels
- Verbose logging levels
- File-based logging
- Combined stderr and file logging
Resolves #405
> Document glog configuration levels in sysconfig.template

- src/netlink/nl_l3.cc
Currently we unconditionally delete the IPv6LL route when it get's deleted from the routing table. But this is a per-interface route, so just because one route is removed does not mean that there are none left.
So the following sequence
$ ip link set up port1
$ ip link set up port2
$ ip link set down port1
will result in the IPv6LL route being disabled, although port1 still has one.
So add a check on deletion if there are any remaining interfaces left with the IPv6LL route, and only actually delete it if there aren't any.
> nl_l3: keep IPv6LL route enabled if any interface still has it

- Makefile
Backport of https://github.com/bisdn/basebox/pull/462.
While we won't need to create new major releases from this branch, we do want minor and especially patch releases, so let's add these here as well.
> 1.x: fix and extend the bumpversion* make targets

- .github/workflows/linter.yml
Change/update the linter configuration:
* change default branch to main
* always lint pull requests, regardless of the target branch
* don't lint pushes, except for main and any stable branch ([1-9].*)
> update linter settings
